### ISSUE TITLE
Schematics Bug

### ISSUE THREAD

**Issue by RageKB** [IntellectualSites/FastAsyncWorldEdit#1183] opened 2021-07-13 21:59 UTC
### Server Implementation

Spigot

### Server Version

1.17.+

### Describe the bug

When I paste a schematic, I do // undo and paste it again, I get an error in the console and print it in half

### To Reproduce

import schematic
/schematic list
click on + to the schematic
//paste
//undo
//paste

### Expected behaviour

that paste the schematic again without cutting a piece and giving an error in the console

### Screenshots / Videos

//

### Error log (if applicable)

[ERROR] An unexpected error while handling a WorldEdit command  java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 20343  at com.sk89q.worldedit.world.block.BlockType.withPropertyId(BlockType.java:142) ~[?:?]  at com.sk89q.worldedit.world.block.BlockType.withStateId(BlockType.java:147) ~[?:?]  at com.sk89q.worldedit.world.block.BlockState.getFromInternalId(BlockState.java:91) ~[?:?]  at com.sk89q.worldedit.extent.transform.BlockTransformExtent.transform(BlockTransformExtent.java:514) ~[?:?]  at com.sk89q.worldedit.extent.transform.BlockTransformExtent.transformBlock(BlockTransformExtent.java:461) ~[?:?]  at com.sk89q.worldedit.extent.transform.BlockTransformExtent.getFullBlock(BlockTransformExtent.java:476) ~[?:?]  at com.fastasyncworldedit.core.object.function.block.SimpleBlockCopy.apply(SimpleBlockCopy.java:20) ~[?:?]  at com.sk89q.worldedit.function.visitor.RegionVisitor.resume(RegionVisitor.java:65) ~[?:?]  at com.sk89q.worldedit.function.operation.Operations.completeBlindly(Operations.java:76) ~[?:?]  at com.sk89q.worldedit.function.operation.ForwardExtentCopy.resume(ForwardExtentCopy.java:395) ~[?:?]  at com.sk89q.worldedit.function.operation.Operations.completeLegacy(Operations.java:57) ~[?:?]  at com.sk89q.worldedit.command.ClipboardCommands.paste(ClipboardCommands.java:437) ~[?:?]  at com.sk89q.worldedit.command.ClipboardCommandsRegistration.cmd$_paste(ClipboardCommandsRegistration.java:333) ~[?:?]  at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]  at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:697) ~[?:?]  at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:713) ~[?:?]  at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:699) ~[?:?]  at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$13(PlatformCommandManager.java:669) ~[?:?]  at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:697) ~[?:?]  at com.fastasyncworldedit.core.object.task.AsyncNotifyQueue.lambda$run$0(AsyncNotifyQueue.java:27) ~[?:?]  at com.fastasyncworldedit.core.object.task.AsyncNotifyQueue.lambda$call$1(AsyncNotifyQueue.java:44) ~[?:?]  at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(Unknown Source) [?:?]  at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?]  at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?]  at java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?]  at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?]  at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?]

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/5df020885774438d80e4873a7f3c3286

### Fawe Version

1.17-52;d7763c8

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by NotMyFault** [comment] 2021-07-13 22:14
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1183

**Closed by NotMyFault** 2021-07-13 22:14 UTC
Labels: Duplicate
