### ISSUE TITLE
//rep ##<anypattern> <block>  throws error "Too many Arguments"

### ISSUE THREAD

**Issue by sixtus18** [IntellectualSites/FastAsyncWorldEdit#1646] opened 2022-03-06 18:34 UTC
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

Replacing a pattern like ##carpets with anything else throws the Error "Too many Arguments"

Example: //rep ##carpets 0

### To Reproduce

1. Select a Region
2. Try to replace some blockpattern like ##carpets with something else
3. Error gets thrown

### Expected behaviour

The Blockpattern should be replaced by the specified Block

### Screenshots / Videos

https://user-images.githubusercontent.com/75905993/156937027-edb00f34-6c6c-478c-9185-f8e1619e7eee.mp4

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/601c3616489d486a829a23ef0c407681

### Fawe Version

FastAsyncWorldEdit 2.0.2-SNAPSHOT-106;081d8dd

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment] 2022-03-06 20:51
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1532

**Closed by NotMyFault** 2022-03-06 20:51 UTC
