### ISSUE TITLE
Undo of chest and signs previously replaced by each other makes them empty and invisible.

### ISSUE THREAD

**Issue by TheoRetisch1** [IntellectualSites/FastAsyncWorldEdit#1567] opened 2022-01-27 12:17 UTC
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

If you replace an existing chest, or sign via `//copy` +`//paste` with a new chest or sign and then undo this action with `//undo`, the original chest and sign are empty and invisible. 

### To Reproduce

1. Place a filled chest and a labelled sign in your world
1. Copy a filled chest and a labelled sign
2. Paste the filled chest and the labelled sign over the existing chest + sign
3. //undo the action
-> the original box and sign are invisible and empty

### Expected behaviour

`//undo `should restore the original state of the filled chest and the labelled sign.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/bb0ff656dc67449f90ccc876c5e47ac6

### Fawe Version

FastAsyncWorldEdit version 2.0.1-SNAPSHOT-76;e8f72d6

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment] 2022-01-27 15:39
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1548 I guess?

**Closed by NotMyFault** 2022-01-27 15:39 UTC

**Comment by TheoRetisch1** [comment] 2022-01-28 09:29
I'm not so sure about that. `//copy` and `//paste` of chest contents has always worked 100%. There were no difficulties at all with the copied content. The difficulties only occur as soon as you try to restore the original state of the world with `//undo`. But if you say it's technically the same problem, thanks for merging.
