### ISSUE TITLE
Polyhedral places blocks randomly

### ISSUE THREAD

**Issue by PeelyMell** [IntellectualSites/FastAsyncWorldEdit#2579] opened 2024-02-07 21:08 UTC
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

I select 3 points and write //re 0 133, as a result, some blocks are placed normally, and some randomly around the selection

### To Reproduce

1. //pos1
2. //pos2
3. //pos2
4. //re 0 133

### Expected behaviour

I expected all the blocks to be placed normally

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/aa475ca4b591480e87e777649a1f706b

### Fawe Version

FastAsyncWorldEdit version 2.9.1-SNAPSHOT-659;c93ec87

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by OneLiteFeather** [comment] 2024-02-08 20:58
Can reproduce that there is something off, but with paper 1.20.4 and need to look if this is an upstream issue as well

**Comment by NotMyFault** [comment] 2024-02-13 15:25
I'm unable to replicate the issue with the steps provided. The outcome matches my selection perfectly:

![Screenshot 2024-02-13 at 16 24 53](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/13383509/37c7f921-0a8b-4fb8-8f7a-3555f60014f3)

Please provide a more descriptive summary of how the outcome looks like and what you expect it to look like.

**Comment by OneLiteFeather** [comment] 2024-02-13 15:27
I managed to replicate it with the third position being on a different y than the others, making a 3D Triangle

**Comment by thomasmny** [comment] 2024-02-13 15:36
Is this a duplicate of #2495?

**Comment by OneLiteFeather** [comment] 2024-02-13 15:55
> Is this a duplicate of #2495?

yeah, we can continue here, thanks for let us know

**Closed** 2024-06-19 05:38 UTC
Labels: [✖] Cannot Replicate
