### ISSUE TITLE
//stack bug with Error code

### ISSUE THREAD

**Issue by AusterAlarm** [IntellectualSites/FastAsyncWorldEdit#1393] opened 2021-11-02 18:36 UTC
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

I want to stackup 40 without air and this error show up.

### To Reproduce

//stack 40 -a

### Expected behaviour

i want to use worldedit to stackup and i want to ignore air blocks with -a

### Error log (if applicable)

https://paste.gg/p/anonymous/3075d55950204450809f15aff9b2c191

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/e287c95545b648c8a167848cec946c70

### Fawe Version

FastAsyncWorldEdit version 1.17-384;a716dd3

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by NotMyFault** [comment] 2021-11-02 18:38
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1384

**Closed by NotMyFault** 2021-11-02 18:38 UTC
Labels: Invalid
