### ISSUE TITLE
Issue With Undo not removing 

### ISSUE THREAD

**Issue by DocCodeSharp** [IntellectualSites/FastAsyncWorldEdit#1145] opened 2021-06-26 05:11 UTC
### Server Implementation

Spigot

### Server Version

1.17.+

### Describe the bug

When you undo something in the world it does not seem to always work. It looks to be something with where the blocks are to the chunks, but I have not got that far. Does not happen all the time.

### To Reproduce

1. Copy blocks.
2. Paste in the world.
3. Undo said paste.

### Expected behaviour

Should remove all blocks in the paste.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/583f385413fe4cceb0a8021a5388ba79

### Fawe Version

FastAsyncWorldEdit-Bukkit-1.17-12.jar

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ or an experimental build and the issue still persists.

**Comment by NotMyFault** [comment] 2021-06-26 09:06
Can't replicate based on the information provided. Please provide some additional information.

**Comment by OstriySous-dev** [comment] 2021-06-27 08:10
The same thing. Chunks are torn at the command and everything does not return.

**Comment by BuggyAl** [comment] 2021-07-06 18:59
not sure if this is the same problem, but using //caves cannot be undone

**Comment by NotMyFault** [comment] 2021-07-07 11:54
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1138

**Closed by NotMyFault** 2021-07-07 11:54 UTC
Labels: More information needed, Requires Testing
