### ISSUE TITLE
/schem list throws NoSuchFileException if per-player schems are enabled but UUID folder is missing

### ISSUE THREAD

**Issue by Kopo942** [IntellectualSites/FastAsyncWorldEdit#1676] opened 2022-03-23 23:33 UTC
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

If a player executes /schem list when
1) per-player schematics are enabled but the player hasn't created a schematic (= /schematics/UUID/ folder is missing), and
2) schematics exist in the parent schematic directory `/FAWE/schematics/`,

a `NoSuchFileException` is thrown for every file in the parent schematic directory. The schematics are listed in-game, but are shown as empty (0.0 kb).

This happens because FAWE is using the per-player folder as the current working directory to access the parent's files (`/UUID/../`). Since the folder doesn't exist, errors are thrown.

### To Reproduce

1. Have some schematics in the root of the schematics folder
2. Enable per-player schematics
3. Make sure the UUID folder for the player executing the command is missing
4. Execute `/schem list`
5. Observe errors thrown in the console for every schematic in the root folder

### Expected behaviour

- No errors thrown
- Files in the root directory to be shown normally

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/034bc99370164a83b6093d6ea66a8f5f

### Fawe Version

FastAsyncWorldEdit version 2.1.1-SNAPSHOT-134;465c81d

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by Blocky38** [comment] 2022-03-24 08:36
I think it is a duplicate of #1235

**Comment by NotMyFault** [comment] 2022-03-27 07:53
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1235

**Closed by NotMyFault** 2022-03-27 07:53 UTC
Labels: Invalid
