### ISSUE TITLE
Error on //regen 1.17 FAWE

### ISSUE THREAD

**Issue by ryzech** [IntellectualSites/FastAsyncWorldEdit#1191] opened 2021-07-22 01:53 UTC
### Server Implementation

Purpur

### Server Version

1.17.+

### Describe the bug

When i use //regen no matter the size, it throws an error and doesnt work as expected.

### To Reproduce

1. select a region
2. use //regen
3. wait
4. it says an error has occured check console

### Expected behaviour

Select a region
Use //regen
it successfully goes through and works

### Error log (if applicable)

https://paste.gg/p/anonymous/5a3a3035c5c04853ad2d78d252091fe6

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/6ac1b96785a54d18927eb9514ba4199d

### Fawe Version

1.17-67;1e49f59

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by MattBDev** [comment] 2021-07-22 05:02
Duplicate of IntellectualSites/FastAsyncWorldEdit-Adapters#8

**Comment by MattBDev** [comment] 2021-07-22 05:02
Duplicate of IntellectualSites/FastAsyncWorldEdit-Adapters#8

**Closed by MattBDev** 2021-07-22 05:02 UTC
Labels: Requires Testing
