### ISSUE TITLE
//smooth -s throws java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ImOlli** [IntellectualSites/FastAsyncWorldEdit#733] opened 2020-11-02 19:54 UTC
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 
https://athion.net/ISPaster/paste/view/23c7c1e3cefb4276b4a4cc19d6293bc5

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):  1.16-432;b728989
- Spigot/Paper Version Number (`/version`):  Paper 253
- Minecraft Version: 1.16.3

**Describe the bug**
If i perform the command "//smooth -s" an error will occur with the following message:
"Please report this error: [See console]
java.lang.Runtime.Exception:
java.lang.ArrayIndexOutOfBoundsException: 16"

The Exception from the console:

```An unexpected error while handling a WorldEdit command
java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 16
        at com.sk89q.worldedit.command.RegionCommands.smooth(RegionCommands.java:436) ~[?:?]
        at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_smooth(RegionCommandsRegistration.java:821) ~[?:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:688) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:704) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:690) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$null$13(PlatformCommandManager.java:660) ~[?:?]
        at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:697) ~[?:?]
        at com.boydti.fawe.object.task.AsyncNotifyQueue.lambda$run$0(AsyncNotifyQueue.java:27) ~[?:?]
        at com.boydti.fawe.object.task.AsyncNotifyQueue.lambda$call$1(AsyncNotifyQueue.java:44) ~[?:?]
        at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(Unknown Source) ~[?:1.8.0_201]
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_201]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_201]
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_201]
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_201]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 16
        at com.boydti.fawe.beta.implementation.blocks.CharBlocks.get(CharBlocks.java:118) ~[?:?]
        at com.boydti.fawe.beta.implementation.blocks.CharBlocks.getBlock(CharBlocks.java:112) ~[?:?]
        at com.boydti.fawe.beta.implementation.chunk.ChunkHolder$2.getBlock(ChunkHolder.java:353) ~[?:?]
        at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.getBlock(ChunkHolder.java:848) ~[?:?]
        at com.boydti.fawe.beta.implementation.IChunkExtent.getBlock(IChunkExtent.java:65) ~[?:?]
        at com.sk89q.worldedit.extent.Extent.getNearestSurfaceLayer(Extent.java:249) ~[?:?]
        at com.sk89q.worldedit.extent.PassthroughExtent.getNearestSurfaceLayer(PassthroughExtent.java:56) ~[?:?]
        at com.sk89q.worldedit.extent.PassthroughExtent.getNearestSurfaceLayer(PassthroughExtent.java:56) ~[?:?]
        at com.sk89q.worldedit.math.convolution.HeightMap.<init>(HeightMap.java:100) ~[?:?]
        at com.sk89q.worldedit.command.RegionCommands.smooth(RegionCommands.java:431) ~[?:?]
        ... 14 more
```

**To Reproduce**
1. Mark a Region with snow layers
2. Use //smooth -s

**Plugins being used on the server**

- VoxelSniper

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.3](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by SirYwell** [comment] 2020-11-02 19:56
Duplicate of #533

**Closed by SirYwell** 2020-11-02 19:56 UTC
Labels: Requires Testing

**Comment by ImOlli** [comment] 2020-11-02 20:05
@SirYwell The referred bug report is open since july. My Team and i need a fix soon!!!

**Comment by SirYwell** [comment] 2020-11-02 20:07
Feel free to fix it. Creating duplicated issues doesn't give us more time to work on it, but rather it wastes our time.

**Comment by ImOlli** [comment] 2020-11-03 07:49
I'm sorry, i didn't saw there was already an duplicate of this. 
I will look if i can fix this issue by myself and request a pull request.
