### ISSUE TITLE
Cannot load from char array because "getSection" is null

### ISSUE THREAD

**Issue by BoomEaro** [IntellectualSites/FastAsyncWorldEdit#1592] opened 2022-01-31 18:40 UTC
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

Randomly, when inserting the schematic, an error occurs that seems to be related to lighting processing.
I'm using WorldEdit API to insert the schematic and seem to be doing everything right using a single thread pool that does something like this:

```
try (EditSession es = WorldEdit.getInstance().newEditSession(w)) {
                Operation op = new ClipboardHolder(cb)
                        .createPaste(es)
                        .to(BlockVector3.at(loc.getX(), loc.getY(), loc.getZ()))
                        .ignoreAirBlocks(false)
                        .copyEntities(false)
                        .copyBiomes(false)
                        .build();

                Operations.complete(op);
            }
```
            
And everything works, however, from time to time, the schematic is inserted incorrectly and an error occurs.

### To Reproduce

The error happens randomly, there is no way to repeat it all the time.

### Expected behaviour

Correct insertion of schematics without errors

### Error log (if applicable)

https://pastebin.com/z5XhDgZd

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/509a03a0c2c9480bb04f91fcc4920819

### Fawe Version

2.0.2-SNAPSHOT-84;faa2477

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by dordsor21** [comment] 2022-02-21 13:29
Likely due to synchronisation issues with the layer or getChunk being trimmed

**Comment by OneLiteFeather** [comment] 2023-04-16 21:47
I saw that in your debugpaste there is a stacktrace before the one you mentioned above. `Failed to locate relight method in LightEngineThreaded on Tuinity. Is everything up to date?` which could be the issue of this problem. This would need a verification.

**Comment by dordsor21** [comment] 2023-04-16 21:58
It's nothing to do with out of date server versions^ as I said most likely due to a rare and slight synchronisation issue. It's somewhat related to other rare issues where changes to the world are not necessarily captured, and typically occur when the queue.target-size config value is hit

**Comment by dordsor21** [comment] 2023-06-11 10:41
Most likely fixed by the recent processSet changes/improvement

**Closed by dordsor21** 2023-06-11 10:41 UTC
Labels: Bug, Approved

**Comment by dordsor21** [comment] 2024-06-08 15:46
It wasn't because I just reproduced, but hopefully #2771 will do something
