### ISSUE TITLE
Unable to paste Block_Display entities.

### ISSUE THREAD

**Issue by LyGend** [IntellectualSites/FastAsyncWorldEdit#2458] opened 2023-10-11 16:04 UTC
### Server Implementation

Paper

### Server Version

1.20.2

### Describe the bug

While single Block_Display entities seems to works perfectly some stacked won't. I use a website to create some Display entitiy creations which the tool gives back a command which spawns all entities at once by let them riding on the first entity.
The one i tested so far is:
[DiamaonCrystalFloor.txt](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/12872019/DiamaonCrystalFloor.txt)

### To Reproduce

1. Create something in https://eszesbalint.github.io/bdstudio/editor.
2. Copy the paste command.
3. Paste it ingame eg. command block or console (Ingame chat is mostly to small).
4. Try to copy and paste it whit FAWE.

### Expected behaviour

I think it is obvious the entities should getting pasted. But not sure if there are some limitations comming to entities i don't know yet.

### Screenshots / Videos

![2023-10-11_17 43 42](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/80472133/bc7526d0-8a03-4b61-bfa0-133e12d4084a)

### Error log (if applicable)

https://pastebin.com/M3ZURCtj

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/93799751cdba427192142a228c6ccc1c

### Fawe Version

2.8.2-SNAPSHOT-581;186d24b

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by LyGend** [comment] 2023-10-13 17:58
Okay i did a little more of testing. Result:
As soon a Block_Display is riding (see screenshots), FAWE is unable to paste the Block_Display which is the Passenger.
So the concept from this "bdstudio" is quite nice to let all display entities riding one to paste them at once is nice. But if FAWE is unable to paste it again ... or even have some trouble to copy it corect, i have to do a workaround to Dismount all this entities. How ever would still be amazing if this is actually a fixable bug from FAWE's side :)
![2023-10-13_19 53 40](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/80472133/e84ea2bb-997d-43ea-869e-ecd855144f30)
![2023-10-13_19 53 43](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/80472133/3e442a13-eb34-48ff-8788-58198b81cbf7)

**Comment by dordsor21** [comment] 2023-10-13 18:29
I'm gonna say this is a duplicate of #2427 then

**Closed by dordsor21** 2023-10-13 18:29 UTC
Labels: Requires Testing
