### ISSUE TITLE
RE: fawe Crashing on certain commands - Tested on git-Paper-64, can't reproduce. This appears to be a mapping issue at Purpurs end.

### ISSUE THREAD

**Issue by narcarsiss** [IntellectualSites/FastAsyncWorldEdit#1155] opened 2021-06-30 00:07 UTC
Tested on git-Paper-64, can't reproduce. This appears to be a mapping issue at Purpurs end.

_Originally posted by @NotMyFault in https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1154#issuecomment-870832674_

## Expected behavior

> Trees should be generating on selected region

## Observed/Actual behavior

  Command not working.
  > **`//regen`**
  https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1154
  
  > **`//forestgen`**
  
![image](https://user-images.githubusercontent.com/3479268/123877873-5da47680-d981-11eb-976d-169288cdd2aa.png)

  
  > **`//brush tree <tree type>`**
  
![image](https://user-images.githubusercontent.com/3479268/123878529-9264fd80-d982-11eb-9932-5240e9ee2032.png)

## Steps/models to reproduce
  See images, has steps on how to reproduce
> Select Cuboid Region with `//Pos1` - `//pos2`
> Selected Arrow in hand
>narcarsiss issued server command: `//forestgen darkoak`

With same region selected or unselected
> issued server command: `//brush tree darkoak`

## Purpur, Paper, Tuinity version

`>version`
> Checking version, please wait...
> This server is running **Latest versions of each as of posting** `(MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)`
> You are running the latest version

## Agreements
Please agree to the following.
- [+] I am running the latest version of **Software** available from each Github Page.
- [+] I have searched for and ensured there isn't already an open issue regarding this.
- [+] My version of FAWE is supported by **Server Software**.

## Other

As per the comment from @Encode42 on Discord I have been able to Reproduce issue in Fresh download of Tuinity, Purpur and Paper.

Only Plugins are.
> EssentialsX-2.19.0-dev+167-9bd35a2
> FastAsyncWorldEdit-Bukkit-1.17-21
> WorldEditSelectionVisualizer-2.0.8
> Fresh Install no configs moved from previous Installs.
> Freshly created Single player world 1.17 moved into Server folder

**Comment by jpenilla** [comment] 2021-06-30 00:44
This seems to be completely unrelated to #1154, the stacktrace here doesn't even look similar.

I re-tested #1154 and confirmed it is fixed in the latest builds of Paper and Tuinity.

This new, separate issue I can confirm however. I get a similar stacktrace when attempting to run `//wand` on the latest Paper and Tuinity.

**Comment by SirYwell** [comment] 2021-06-30 06:35
Duplicate of #1148.

Also, fill out the issue template properly the next time - it exists for a reason.

**Closed by SirYwell** 2021-06-30 06:35 UTC
