### ISSUE TITLE
limits.strip-nbt not working

### ISSUE THREAD

**Issue by Over2Craft-mc** [IntellectualSites/FastAsyncWorldEdit#939] opened 2021-02-26 15:42 UTC
**Describe the bug**

limits.strip-nbt is not working. When a player is affected by a limit which contains block to strip nbt from, nbt are not stripped. 

**To Reproduce**

1. Configure a limit for example 
```yml
limits:
  default:
    max-actions: 1
    max-changes: 5
    max-checks: 5
    max-fails: 5
    max-iterations: 1000
    max-entities: 1337
    max-blockstates: 0
    max-history-mb: -1
    max-expression-ms: 50
    speed-reduction: 0
    fast-placement: true
    inventory-mode: 0
    confirm-large: true
    # List of blocks to strip nbt from
    strip-nbt: 
    - "minecraft:chest"
    - "CHEST"
```

2. Place some item in a chest

3. Give default limit permissions 

4. Copy paste the chest

**Expected behaviour**

Content of the chest shouldn't be copied if it is listed in "strip-nbt".

**Screenshots / Videos**

_No response_

**Error log (if applicable)**

_No response_

**Fawe Debugpaste**

https://athion.net/ISPaster/paste/view/18e46f3a021a42d98ba66adb829f0de8

**Fawe Version**

Fastasyncworldedit Version: 1.16-612;1a3f479

**Additional Context**

_No response_

**Comment by Over2Craft-mc** [comment] 2021-03-10 21:08
Hi there,

Just to report that this is pretty critical and most of servers might not be able to update FAWE on public creative server if FAWE has this issue. It make it very easy for people to crash server if nbt cannot be stripped.

**Comment by AMDBartek** [comment] 2021-03-10 23:07
Yeah, this can be a serious issue on creative servers.

**Comment by BatchWhoAmI** [comment] 2021-03-14 13:59
It's 16 days old and the issue is still not fixed?

**Comment by SirYwell** [comment] 2021-03-14 14:08
As you can see, yes.

**Comment by BatchWhoAmI** [comment] 2021-03-14 14:12
It is a critical issue so please fix it asap

**Comment by Over2Craft-mc** [comment] 2021-03-14 19:14
Yeah, I whish priority label would be added

For those who want a work arround toi can use this https://www.spigotmc.org/resources/insights-super-configurable-region-limits-asynchronous-scans-1-15-1-16-5.56489/ to block edition on block that contains some nbt (like chest, banner)...

**Comment by aurorasmiles** [comment] 2021-03-14 19:20
there you go, not that it makes a difference

**Comment by SirYwell** [comment] 2021-03-14 19:56
From a quick look at the code, the comment in the config is wrong. Actually, it strips the configured NBT keys from blocks, so for chests you need to add `Items` to that section.

**Comment by Over2Craft-mc** [comment] 2021-03-16 15:46
> From a quick look at the code, the comment in the config is wrong. Actually, it strips the configured NBT keys from blocks, so for chests you need to add `Items` to that section.

True, this worked.

**Comment by NotMyFault** [comment] 2021-04-12 11:46
Closing in favor of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/939#issuecomment-798969262

**Closed by NotMyFault** 2021-04-12 11:46 UTC
Labels: Approved, Bug, Priority
