### ISSUE TITLE
CFI error Unable to generate world

### ISSUE THREAD

**Issue by seijichurro** [IntellectualSites/FastAsyncWorldEdit#138] opened 2019-04-29 18:13 UTC
# Bug report for FastAsyncWorldEdit 1.13.2

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

29.04 19:52:55 [Server] INFO [19:52:55 INFO]: (FAWE) FastAsyncWorldEdit 1.13-19.4.28-3ffa54a-103 by Empire92
29.04 19:52:55 [Server] INFO [19:52:55 INFO]: ------------------------------------
29.04 19:52:55 [Server] INFO [19:52:55 INFO]:  - DATE: Apr 28, 2019 12:00:00 AM
29.04 19:52:55 [Server] INFO [19:52:55 INFO]:  - COMMIT: 3ffa54a
29.04 19:52:55 [Server] INFO [19:52:55 INFO]:  - BUILD: 103
29.04 19:52:55 [Server] INFO [19:52:55 INFO]:  - PLATFORM: bukkit
29.04 19:52:55 [Server] INFO [19:52:55 INFO]: ------------------------------------
29.04 19:52:55 [Server] INFO [19:52:55 INFO]: Platforms:
29.04 19:52:55 [Server] INFO [19:52:55 INFO]:  - Bukkit (1.13.103)
29.04 19:52:55 [Server] INFO [19:52:55 INFO]: Capabilities:
29.04 19:52:55 [Server] INFO [19:52:55 INFO]:  - GAME_HOOKS: Bukkit
29.04 19:52:55 [Server] INFO [19:52:55 INFO]:  - CONFIGURATION: Bukkit
29.04 19:52:55 [Server] INFO [19:52:55 INFO]:  - USER_COMMANDS: Bukkit
29.04 19:52:55 [Server] INFO [19:52:55 INFO]:  - PERMISSIONS: Bukkit
29.04 19:52:55 [Server] INFO [19:52:55 INFO]:  - WORLDEDIT_CUI: Bukkit
29.04 19:52:55 [Server] INFO [19:52:55 INFO]:  - WORLD_EDITING: Bukkit
29.04 19:52:55 [Server] INFO [19:52:55 INFO]: ------------------------------------
29.04 19:52:55 [Server] INFO [19:52:55 INFO]: Wiki: https://github.com/boy0001/FastAsyncWorldedit/wiki

**[REQUIRED] Spigot/Paper Version Number:** 
 29.04 19:53:01 [Server] INFO [19:53:01 INFO]: This server is running CraftBukkit version git-Spigot-518206a-a5b9c7b (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
29.04 19:53:01 [Server] INFO [19:53:01 INFO]: You are 176 version(s) behind

**Links to config.yml and config-legacy.yml file:** 

config.yml - https://www.hastebin.com/akuyepugel.coffeescript
config-legacy.yml - https://www.hastebin.com/dikehugaqu.bash

**[REQUIRED] Description of the problem:**
 https://www.hastebin.com/umosiqosuc.sql
 http://i.imgur.com/qCd30MR.jpg
For some odd reason I cannot seem to generate a world in CFI. I've tried multiple things and I asked for support in discord and all I got was to say I should make a post in here. I apologize if my post and english seems off, english is not my first language. this is also my first time in github so bare with me please.
it keeps on saying "unable to generate world... (see console)?"
"Unable to import world (region) please do so manually"

**Plugins being used on the server:**

**How to replicate**:

https://imgur.com/a/pAibCcB
So what I basically did was
1. //cfi - I picked heightmap and i copy pasted the link used in the example ( the "[this]" message), i obviously used URL.
2. I practically did the same with the coloring using the given example link.
3. I go back and click on done, and it just says the error given from the screenshot.
"Unable to generate world... (See console)?"
"Unable to import world (region) please do so manually"

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.13.2](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
- [] I made sure the bug/error is not caused by any other plugin

**Comment by PhilippUlti** [comment] 2020-11-03 10:05
//cfi has not been implemented for a long time and version 1.13.2 will not be developed any further. The issue is no longer necessary

**Comment by dordsor21** [comment] 2020-12-16 18:23
closing in favour of #552

**Closed by dordsor21** 2020-12-16 18:23 UTC
