### ISSUE TITLE
Problem /br sweep

### ISSUE THREAD

**Issue by Temale62** [IntellectualSites/FastAsyncWorldEdit#419] opened 2020-04-23 20:35 UTC
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/41694b834555411f84db02b1558f2f5f

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
FastAsyncWorldEdit-1.15-177.jar

**[REQUIRED] Spigot/Paper Version Number:** 
git-Paper-211 (MC: 1.15.2)

**[REQUIRED] Description of the problem:**

Hello, 
I have a problem on FAWE when I do my left clicks after a /br sweep, warn is created in the console, and the /br sweep does not work
is it a dev build problem or a bad parameter on my side?

Thank you in advance

**Comment by Temale62** [comment] 2020-04-23 20:36
>.... [22:36:05 WARN]: java.lang.NullPointerException
>.... [22:36:05 WARN]: at com.sk89q.worldedit.math.BlockVector3.equals(BlockVector3.java:768)
>.... [22:36:05 WARN]: at com.boydti.fawe.object.brush.sweep.SweepBrush.build(SweepBrush.java:48)
>.... [22:36:05 WARN]: at com.sk89q.worldedit.command.tool.BrushTool.act(BrushTool.java:470)
>.... [22:36:05 WARN]: at com.sk89q.worldedit.command.tool.BrushTool.actPrimary(BrushTool.java:366)
>.... [22:36:05 WARN]: at com.sk89q.worldedit.extension.platform.PlatformManager.lambda$handlePlayerInput$4(PlatformManager.java:433)
>.... [22:36:05 WARN]: at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:671)
>.... [22:36:05 WARN]: at com.boydti.fawe.object.task.AsyncNotifyQueue.lambda$run$0(AsyncNotifyQueue.java:26)
>.... [22:36:05 WARN]: at com.boydti.fawe.object.task.AsyncNotifyQueue.lambda$call$1(AsyncNotifyQueue.java:43)
>.... [22:36:05 WARN]: at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
>.... [22:36:05 WARN]: at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
>.... [22:36:05 WARN]: at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
>.... [22:36:05 WARN]: at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
>.... [22:36:05 WARN]: at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by aurorasmiles** [comment] 2020-04-24 06:43
confirmed in 178

**Comment by aurorasmiles** [comment] 2020-04-24 10:35
Actually, sorry, this is a duplicate of #306 - missed that one

**Comment by Temale62** [comment] 2020-04-24 10:36
oops, sorry

**Comment by aurorasmiles** [comment] 2020-04-24 14:18
Duplicate of #306

**Closed by aurorasmiles** 2020-04-24 14:18 UTC
Labels: Approved, [!] Bug
