### ISSUE TITLE
Maps don't update after WE job

### ISSUE THREAD

**Issue by nirewen** [IntellectualSites/FastAsyncWorldEdit#438] opened 2020-05-01 21:35 UTC
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

https://athion.net/ISPaster/paste/view/e579d7674b984cea9b42fccf134415bd

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

```
[23:20:27 INFO]: FastAsyncWorldEdit-192 created by Empire92
[23:20:27 INFO]: FAWE version:
- Date Apr 30, 2020, 12:00:00 AM
- Commit fa04e7db
- Build 192
- Platform Bukkit
[23:20:27 INFO]: Wiki: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki
[23:20:27 INFO]: ------------------ Platforms ------------------
* Bukkit-Official(1.15-192;5fb1825)
[23:20:27 INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official
```

**[REQUIRED] Spigot/Paper Version Number:** 

This server is running Tuinity version git-Tuinity-"99854e9" (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**[REQUIRED] Description of the problem:**

After doing a WE job, maps (the item) are not updated.
I just did, using the latest FAWE version in my test server to see if it was fixed already and I didn't know.
Screenshot:
![2020-05-01_18 14 24](https://user-images.githubusercontent.com/8761479/80842809-f6523180-8bd8-11ea-9807-495f94087f30.png)

The thing is, this is a very old bug, I remember it in 1.12 or something. Everytime I needed the map to update, I had to create a huge 128x128 platform and fill it with water to update. Or even use /fill from vanilla Minecraft which sometimes crashed the server.
I really hope this bug can be fixed. I'll understand if this is a side effect of the way FAWE works and it can't be fixed.

**How to replicate**:

1. Open a map
2. Select two points
3. Start a WE job (//set, //replace, etc.)

**Plugins being used on the server:**

Plugins (26): ArmorStandTools, AuthMe, BKCommonLib, DiceFurniture, EhChat, EhCore, EhPlots, EnhancedDebugStick, FastAsyncWorldEdit, FastLogin, FurnitureLib, LiteBans, LuckPerms, PlaceholderAPI, PlotSquared, PlugMan, ProtectionLib*, ProtocolLib, SimpleAFK, SkinsRestorer, TAB, Train_Carts, Vehicles, VehiclesPlotSquared, VoidGenerator, WorldEdit

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment] 2020-05-01 22:15
I won't close this right now but this is likely a side effect of FAWE because it modifies ChunkSections.

**Comment by dordsor21** [comment] 2020-05-01 22:28
I know what the issue is I think, I just need to do something about it at some point

**Comment by dordsor21** [comment] 2020-05-11 12:49
I think this is related to the rain issue. Presumably maps also use heightmaps

**Comment by Rhonim** [comment] 2020-08-09 19:45
This is still an issue in 1.16.1 as well

**Closed** 2020-09-14 13:19 UTC
Labels: Requires Testing

**Comment by BurkenDev** [comment] 2021-01-16 14:36
Still issue in 1.16.4. Maps still don't update after any worldedit job
