### ISSUE TITLE
Extra territory is removed

### ISSUE THREAD

**Issue by NewJeb** [IntellectualSites/FastAsyncWorldEdit#1237] opened 2021-08-18 22:07 UTC
Edited to remove the needlessly rude and aggressive language. This person be mad.

### Server Implementation

Purpur

### Server Version

1.17.1

### Describe the bug

I wanted to delete the selected area (it is highlighted in green, everything is intact because I used / undo to see if the territory on the right will recover (no)), as a result, the territory on the right retreated with it. This is not the first time, and not only from the action to remove the territory.

### To Reproduce

1. Allocate territory (or do something else)
2. Remove or use brush

### Expected behaviour

That the territory will be removed in the right place

### Screenshots / Videos

![2021-08-18_14 42 16](https://user-images.githubusercontent.com/50917369/129978260-6e29bc74-a553-46c1-b45a-71c74db90ac3.png)
![2021-08-18_14 44 45](https://user-images.githubusercontent.com/50917369/129978286-b4397ae5-4fcc-436d-b77b-1bea25db4fb7.png)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/5708514eef3645e8a619f39c1690e7dc

### Fawe Version

1.17-159;f258a3d

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by NotMyFault** [comment] 2021-08-18 22:08
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1169 ?

**Comment by dordsor21** [comment] 2021-08-18 22:20
Not a duplicate f that at all... Please try without purpur and see if this issue can be replicated on Paper.

**Comment by Combustible** [comment] 2021-08-28 17:28
Ah good, glad to see this bug exists. We are also on 1.16 Paper and seeing this problem all over the place. This bug was introduced somewhere between build 127 and 187.

FAWE version: Bukkit-Official(1.17-187;ee14f7e)
Paper version: 1.16.5 build 778 - [903fa9a] Enable chunk load for feature search by default | 2021-06-16

What we are seeing is that sometimes when an area is pasted, the chunk sections adjacent to that area are destroyed. Here's a particularly good example: 

![FAWE damaged area](https://user-images.githubusercontent.com/2737074/131225644-4a99e189-2a4e-4441-9598-f649385c504a.png)

The floating wall segment is a door to this pyramid that was paste'd in (in this dungeon this door starts closed/bedrocked, then an open version gets paste'd on top of it). But the area around it is removed by FAWE in addition to placing the area. 

You can see in this picture that the damage is chunk section aligned. However, note also that not everything in that chunk section is damaged - there are still some bedrock blocks that didn't get destroyed that are outside the selection area. 
![2021-08-28_10 23 16](https://user-images.githubusercontent.com/2737074/131225854-ab8ebc8d-06d6-4589-ac4c-430edd7bf3bd.png)

Here's another strange instance, where this island to the right got paste'd in, and a border around it was destroyed.... except for some granite?
![2021-08-28_10 25 03](https://user-images.githubusercontent.com/2737074/131225879-2c7abf6d-305a-4fd8-868f-1a90a95ddfeb.png)

This is definitely a big problem for us though, we are rolling back FAWE today and restoring backups. This definitely doesn't happen every time - maybe one in 50 times? Definitely frequent, we have a lot of damage all over the place, but rare enough to be annoying to reproduce. 

Maybe this is a chunk palette saving issue? Not sure...

**Comment by Combustible** [comment] 2021-08-28 17:48
Looks like the bug was reported on build 159, and I know 127 didn't have this problem. Looking at commits between the two, my guess is one of these: 

#138 (Aug 14, 2021 1:35:04 PM)
    Minecraft uses the global block palette if there are more than 8 bits per entry in a chunk section (commit: c287739) — dordsor21 / githubweb

#141 (Aug 17, 2021 12:50:05 AM)
    Add basic preloading (#1221) (commit: da7aca8) — github / githubweb
  
    
But I'm really just guessing.

**Comment by Combustible** [comment] 2021-08-28 18:00
Looks like someone posted an update to #1169 which I believe was actually this bug, reported using build 139. So that narrows the version range down even further to 127 -> 139. My bet is definitely on the global palette changes at this point.

**Comment by dordsor21** [comment] 2021-08-29 09:27
@Combustible Is this also on the first edit for you?

**Comment by Combustible** [comment] 2021-08-30 03:26
Huh, that's a really good question - it's definitely possible it's only happening on first edit, my server automatically restarts once a day. 

I see that change made its way into build 191. I'm going to pick that up and try it out - I still haven't repaired the damage to my world from before so it's probably going to take me a couple days to know for sure whether new damage appears or not.

**Comment by almic** [comment] 2021-08-30 20:09
I am definitely seeing this problem still with 190, which says to have the fix for these bugs (commit ebc38a6). I had this a few days ago but didn't think to report it, I chalked it up to having just upgraded everything to 1.17 and ignored the massive holes it created off the side of a build. I was just doing an //undo because I used //outline incorrectly and it left holes right next to me. The selection was massive but only those chunks in render distance, and only in one direction, seem to be messed up. Also, you might be happy to know that it didn't mess up chunks outside the selection, although that can just be because my selection was exactly on chunk edges...

![2021-08-30_14 07 36](https://user-images.githubusercontent.com/21991767/131398728-81521910-14a6-4d54-bea5-22df8b708950.png)

**Comment by dordsor21** [comment] 2021-08-30 20:10
The latest build is 191...

**Comment by almic** [comment] 2021-08-30 20:16
okay for some reason it says 190 is based on the commit here https://ci.athion.net/job/FastAsyncWorldEdit-1.17/190/, sorry for being confused, I'll update and see if it's still happening

**Comment by Combustible** [comment] 2021-09-04 18:42
Virtually certain this is fixed at this point, we've had several restarts & a lot of stuff loading & saving without encountering this issue again, using build 191. 

Thanks @dordsor21 for the fix!

**Closed** 2021-09-06 11:41 UTC
Labels: Bug, Approved, Requires Testing
