### ISSUE TITLE
//flip spams console with warnings

### ISSUE THREAD

**Issue by BullobilyMC** [IntellectualSites/FastAsyncWorldEdit#1166] opened 2021-07-03 22:26 UTC
### Server Implementation

Purpur

### Server Version

1.16.5

### Describe the bug

Using //flip command works well but spams the console with warnings.

### To Reproduce

Select an area (mine was of 7000 blocks)
Copy it (//copy)
Flip it (//flip)
Paste it (//paste -a)

See warnings in console

### Expected behaviour

Just the same without warnings

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/f93af8893ca742fb9f3434c2a09d65b3

### Fawe Version

FastAsyncWorldEdit version 1.17-41;4f4f3ea

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by NotMyFault** [comment] 2021-07-03 22:29
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1122

**Closed by NotMyFault** 2021-07-03 22:29 UTC
Labels: Duplicate
