### ISSUE TITLE
Actions with an active //gmask don't seem to work often

### ISSUE THREAD

**Issue by Feniksovich** [IntellectualSites/FastAsyncWorldEdit#2584] opened 2024-02-13 16:10 UTC
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

Some actions (`//set` at least) don't work with active //gmask the most of time. To be more clear, there is a message action was performed but no expected changes happen actually. Yes, it means it can work at some time.

### To Reproduce

1. Build a test structure. For example, 3 sandstone blocks with 3 stone blocks on top.
2. Set global mask with `//gmask "stone >sandstone"` 
3. Run `//set dirt`
4. See that nothing has happened (stone blocks wasn't replaced to dirt ones actually).

### Expected behaviour

3 stone blocks above sandstone ones in the structure were to be replaced with dirt blocks.

### Screenshots / Videos

<details>
  <summary>Figure</summary>
  
  ![image](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/33875970/a68ef548-ce6d-4bac-b5d4-01c669e946b2)
</details>

### Error log (if applicable)

https://paste.gg/p/anonymous/af66a39bf5c94b738e270d8a023e52a0

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/51bc923d648f46548260e1c946479ca0

### Fawe Version

FastAsyncWorldEdit 2.9.1-SNAPSHOT-659

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

An exception was also noticed during the execution of //set with global mask set (please see error log link).

**Comment by dordsor21** [comment] 2024-02-18 04:12
Duplicate of #2546 I suppose

**Closed by dordsor21** 2024-02-18 04:12 UTC
Labels: Requires Testing
