### ISSUE TITLE
FAWE cuts random cuboids

### ISSUE THREAD

**Issue by CrazyWorldPL** [IntellectualSites/FastAsyncWorldEdit#1258] opened 2021-08-28 15:14 UTC
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

On video, bug doesn't occur when you don't have admin permissions.

### To Reproduce

on video

### Expected behaviour

Proper operation.

### Screenshots / Videos

https://youtu.be/gMhby8Xegwg

### Error log (if applicable)

No errors.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/40391ca38b154264b5fe476c665fb54f

### Fawe Version

FastAsyncWorldEdit version 1.17-190;ebc38a6

### Checklist

- [X] I have included a Fawe debugpaste.
- [x] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by NotMyFault** [comment] 2021-08-28 15:39
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1237

**Closed by NotMyFault** 2021-08-28 15:39 UTC
Labels: Invalid, Duplicate
