### ISSUE TITLE
Improper heightmap updates

### ISSUE THREAD

**Issue by demon2749** [IntellectualSites/FastAsyncWorldEdit#980] opened 2021-03-16 20:02 UTC
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

large edits leave some chunks unedited/corrupt in a map.

### To Reproduce

1. copy a large portion of land
2. paste in another area where the top layer has differing blocks. (over an ocean, etc)
3. create maps
4. note the lack of some chunks being updated on the map.

### Expected behaviour

The expectation would be that all changes are visible once the player returns to updates the maps.

### Screenshots / Videos

https://pasteboard.co/JSVqQA3A.png

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/b070dbbb4b544dbaaf4aeea1748226f8

### Fawe Version

FastAsyncWorldEdit version 1.16-613;32b5261

**Comment by NotMyFault** [comment] 2021-03-16 20:04
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/881

**Closed by NotMyFault** 2021-03-16 20:04 UTC
Labels: Invalid
