### ISSUE TITLE
BeaconDeactivatedEvent may only be triggered synchronously

### ISSUE THREAD

**Issue by PonlawatP** [IntellectualSites/FastAsyncWorldEdit#1109] opened 2021-06-08 09:53 UTC
### Server Implementation

Tuinity

### Server Version

1.16.5

### Describe the bug

that's happened when trying to use replace command in any zone that include Beacon with another block

### To Reproduce

1: //rep 0 with zone including Beacon inside
2: Error and won't does anything else in current chunk. but other chunk was continue worked

### Expected behaviour

everything would be clear when i replace with air

![2021-06-08_16 48 31](https://user-images.githubusercontent.com/48130528/121163927-64a40180-c879-11eb-92e4-c9eb3efb527c.png)

### Screenshots / Videos

![2021-06-08_16 48 38](https://user-images.githubusercontent.com/48130528/121163980-6ff72d00-c879-11eb-888c-fbaa064f13f6.png)

### Error log (if applicable)

https://gist.github.com/PonlawatP/0f8bc0351c8677e5b93acf275da68bc2

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/4dff500d5a7d4c319866b69d9ba8c6ee

### Fawe Version

FastAsyncWorldEdit-Bukkit-1.16-708

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

### Anything else?

I don't know can put this details but in PlotSquared has this issue when reset plot too, but Road Regenerator still work fine

**Comment by NotMyFault** [comment] 2021-06-08 09:56
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1048

**Closed by NotMyFault** 2021-06-08 09:56 UTC
Labels: Duplicate
