### ISSUE TITLE
FAWE removed 3 chunks instead of 13x18 area

### ISSUE THREAD

**Issue by Adreez** [IntellectualSites/FastAsyncWorldEdit#1257] opened 2021-08-27 21:19 UTC
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

I selected grid something like 13x8x7 and after using //set 0 plugin removed all 3 chunks (+1 but on 4th chunk it was only 1 block selected)
![Uploading image.png…]()

I repaired the building with coreprotect but second one was builded before we put coreprotect on server so there wasn´t any data about the blocks. We have allowed in coreprotect config worldedit logging but there wasn´t anything.

### To Reproduce

After //set 0 selected grid has been selected but it removed 3 chunks.

### Expected behaviour

I hoped the selected zone would be deleted 

### Error log (if applicable)

https://paste.gg/p/anonymous/e519b7bfe462476f844bcb60b829901d

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/92d358b2663a45d68471c994a6ffd43c

### Fawe Version

1.17-190;ebc38a6

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

### Anything else?

After //undo nothing happend.

**Comment by NotMyFault** [comment] 2021-08-28 15:39
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1237

**Closed by NotMyFault** 2021-08-28 15:39 UTC
Labels: Requires Testing
