### ISSUE TITLE
Light issue

### ISSUE THREAD

**Issue by AggerTV** [IntellectualSites/FastAsyncWorldEdit#983] opened 2021-03-17 12:01 UTC
### Server Implementation

Tuinity

### Server Version

1.16.5

### Describe the bug

Some blocks are not correctly lighted up, as seen on these images
https://gyazo.com/7976ae6085979f0ce356d5adf8aad197
https://gyazo.com/f079d95acaef710a3fe15fa896669458

to fix the blocks you need to block update them, by e.g interacting with the block

It is not uniform for all players, meaning if the bug is fixed for 1 client, it is still there for another client.

### To Reproduce

I don't have a definitive anwser to what causes this bug, other than simply using fawe

### Expected behaviour

For the blocks to be proper lit

### Screenshots / Videos

https://gyazo.com/7976ae6085979f0ce356d5adf8aad197
https://gyazo.com/f079d95acaef710a3fe15fa896669458

### Fawe Debugpaste

I'll just post the fawe debug log for good measures

### Fawe Version

FastAsyncWorldEdit version 1.16-616;99ea64f

**Comment by LaurenceBarnes** [comment] 2021-03-17 12:19
similar to #857 I guess

**Comment by NotMyFault** [comment] 2021-03-17 12:46
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/857

**Closed by NotMyFault** 2021-03-17 12:46 UTC
Labels: Invalid

**Comment by AggerTV** [comment] 2021-03-18 12:25
I know this issue is closed, but I have a question that I would like to have cleared up.

Switching client versions to e.g minecraft 1.12.2 seems to fix the issue. Is it then really a issue with fawe?

**Comment by LaurenceBarnes** [comment] 2021-03-18 12:53
what matters is not necessarily what the client sees, but what the server calculates. I assume you have ViaBackwards in order to use older clients? It is possible that it does not translate all data properly which can have many reasons.
