### ISSUE TITLE
Tab Completion not working for String Lists in f.e. //replace

### ISSUE THREAD

**Issue by flashbtw** [IntellectualSites/FastAsyncWorldEdit#1584] opened 2022-01-28 21:22 UTC
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

When you type for example `//replace stone dirt,blackstone,calcite`, stone and dirt are getting completed but blackstone and calcite aren't.

### To Reproduce

1. Install FAVS 2.3.0
2. Install FAWE (newest Release 78)
3. try //replace stone dirt,blackstone

### Expected behaviour

The List is supposed to be completed for every block itself.

### Screenshots / Videos

This is working: https://i.imgur.com/pG5d9k5
Not working: https://imgur.com/erWMFpG

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/a2fa2ae88b3c4bec86a2f1fd3d7df7f2

### Fawe Version

FastAsyncWorldEdit-78

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment] 2022-01-28 21:24
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1509

**Closed by NotMyFault** 2022-01-28 21:24 UTC
Labels: Duplicate
