### ISSUE TITLE
Error while executing command "//regen" (Paper - 1.15.2)

### ISSUE THREAD

**Issue by Shark-vil** [IntellectualSites/FastAsyncWorldEdit#659] opened 2020-09-24 04:15 UTC
# Bug report for FastAsyncWorldEdit 1.16-377

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/09bdb54b66e54af0ac6dbe7d56efa082

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
```
[07:05:47 INFO]: FastAsyncWorldEdit-377 created by Empire92, MattBDev, IronApollo, dordsor21 and NotMyFault
[07:05:47 INFO]: FAWE version:
 - Date Sep 22, 2020, 12:00:00 AM
 - Commit fa1983e5
 - Build 377
 - Platform Bukkit
[07:05:47 INFO]: Wiki: https://wiki.intellectualsites.com/FastAsyncWorldEdit/index
[07:05:47 INFO]: ------------------ Platforms ------------------
* Bukkit-Official(1.16-377;5e67c1b)

[07:05:47 INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official
```

**[REQUIRED] Spigot/Paper Version Number:** 
```
[07:06:46 INFO]: This server is running Paper version git-Paper-385 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
```

**[REQUIRED] Description of the problem:**
When trying to re-generate the selected region, an error occurs. (The error message can be seen from the link above)

**How to replicate**:
1. Select first point - //pos1
2. Select second point - //pos2
3. Write a command to the chat - //regen

**Plugins being used on the server:**
```
Plugins (34): AuthMe, ChatControl, ClearLag, CraftBook, CustomStructures, DragonSlayer, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsProtect, EssentialsSpawn,  (WorldEdit)FastAsyncWorldEdit, GMusic, GSit, Jobs, LuckPerms, mcMMO, Multiverse-Core, MythicMobs, OpenInv, PlayerWarps, PlugMan, ProtocolLib, RandomTeleport, SuperVanish, UltimateTimber, Vault, ViaVersion, VillagerBank, VillagerMarket, WorldBorder, WorldEditSUI, WorldGuard, WorldGuardExtraFlags
```

**Comment by aurorasmiles** [comment] 2020-09-24 06:25
Duplicate of #541

**Closed by aurorasmiles** 2020-09-24 06:25 UTC
Labels: Requires Testing
