### ISSUE TITLE
Unable to copy the second time when copying a large building

### ISSUE THREAD

**Issue by ValiantShishu** [IntellectualSites/FastAsyncWorldEdit#385] opened 2020-03-30 09:45 UTC
# Bug report for FastAsyncWorldEdit 1.14.4

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
[latest.log](https://paste.ubuntu.com/p/cxyMQVJD87/)
[config.yml](https://paste.ubuntu.com/p/M79xrmtNzS/) (unedited)
[config-legacy.yml](https://paste.ubuntu.com/p/9mHnc4HRWP/) (unedited)

**[REQUIRED] FastAsyncWorldEdit Version Number:**
```
[18:14:01 INFO]: FastAsyncWorldEditunknown created by Empire92
[18:14:01 INFO]: Wiki: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki
[18:14:01 INFO]: ------------------ Platforms ------------------
* Bukkit-Official(1.15-144;46d24ff)

[18:14:01 INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official
```

**[REQUIRED] Spigot/Paper Version Number:** 
Paper(243) 1.14.4-R0.1-SNAPSHOT

**[REQUIRED] Description of the problem:**
Copy the server building, copy it for the first time, and this error will appear for the second time after pasting or not pasting, and it will return to normal after restarting the server. But I still get this error after repeating the previous operation

**How to replicate:**
The problem is as above, there is an error fragment during execution:https://paste.ubuntu.com/p/r2wRs6Svws/

**Plugins being used on the server:**
Plugins (23): AntiExplosion*, antiRedstoneClock, BossShopPro, CMI, CMIEInjector*, CoreProtect, dynmap*, EliteMobs, FastAsyncWorldEdit, LockettePro, LuckPerms, Multiverse-Core, PlaceholderAPI, ProtocolLib, QuickShop, SaveRodOfficial*, Vault, VeinMiner, ViaVersion*, VillagerOptimiser, VipSystem*, WorldBorder, WorldEdit.

**Checklist**:

- [x] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure the bug/error is not caused by any other plugin
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)

**Comment by dordsor21** [comment] 2020-03-30 11:09
Duplicate of #356

**Closed by dordsor21** 2020-03-30 11:09 UTC
Labels: Requires Testing
