### ISSUE TITLE
Setbiome Does Not Work With 1.18 Heights

### ISSUE THREAD

**Issue by lampmeorelse** [IntellectualSites/FastAsyncWorldEdit#1501] opened 2021-12-27 21:39 UTC
### Server Implementation

Purpur

### Server Version

1.18.1

### Describe the bug

When trying to //setbiome, it works as it should while using it between y=0 and y=256, but if you try it below y=0 or above y=256, it does not work. The following error message is given:

ERROR An unexpected error while handling a FastAsyncWorldEdit command
INFO java.lang.ArrayIndexOutOfBoundsException: null

### To Reproduce

1. Select part of a world that is either below y=0 or above y=256 (Or all the way through)
2. Try `//setbiome forest`
3. An error message will be thrown, and the biome will not be changed.

### Expected behaviour

I mean, it should obviously change the biome like it does for < 1.18 versions.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/6d2228e27295427ba7102eb1d3c9c59a

### Fawe Version

FastAsyncWorldEdit version 2.0.0-SNAPSHOT-24;f9ecb44

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment] 2021-12-27 21:50
Can you replicate that on Paper? I'm not able to.

**Comment by lampmeorelse** [comment] 2021-12-27 22:12
Yes, I was able to recreate this on a fresh paper server, with FAWE being the only plugin installed. 
Latest Paper version, latest FAWE version.
[Paste](https://paste.gg/p/anonymous/fdbd38c0d8b24aaabf3b515d8b48e261)

**Comment by NotMyFault** [comment] 2021-12-27 22:13
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1490

**Closed by NotMyFault** 2021-12-27 22:13 UTC
Labels: Invalid
