### ISSUE TITLE
superpickaxe broken

### ISSUE THREAD

**Issue by kikelkik** [IntellectualSites/FastAsyncWorldEdit#474] opened 2020-05-20 11:13 UTC
FastAsyncWorldEdit Configuration Files:
https://athion.net/ISPaster/paste/view/ee8d044d090543e28928e15f1f51ae0d

FastAsyncWorldEdit Version Number:
WorldEdit version 1.15-245

Spigot/Paper Version Number:
git-Paper-282 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**[REQUIRED] Description of the problem:**
Superpickaxe doesn't check for different materials reliably since 1.15.2.

**How to replicate**:
- //pos1, //pos2, //set 1,4,5
- //sp recursive 3 or //sp area 3
- Hit Cobblestone
=> Not only Cobblestone will be removed (recur seems to act not deterministic, area seems to always break everything within the given radius).

**Plugins being used on the server:**
See https://athion.net/ISPaster/paste/view/ee8d044d090543e28928e15f1f51ae0d

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by pascal541** [comment] 2020-05-20 12:05
#436

**Comment by aurorasmiles** [comment] 2020-05-20 12:08
Duplicate of #436

**Closed by aurorasmiles** 2020-05-20 12:08 UTC
Labels: Requires Testing

**Comment by kikelkik** [comment] 2020-05-20 12:09
sorry for that duplication - I searched in issues for "superpickaxe" and that ticket doesn't occur there o.O
