### ISSUE TITLE
Flora like command for water

### ISSUE THREAD

**Issue by JediM4ster** [IntellectualSites/FastAsyncWorldEdit#1924] opened 2022-08-25 17:02 UTC
### What feature do you want to see added?

Similarly to the flora command. Something that places underwater flora such as sea grass, coral, kelp, etc. based off of whatever water biome it may be in. So that coral only really spawns in warm ocean. Will also spawn things like sea pickles.

### Are there any alternatives?

Nope other than doing it by hand which often takes forever...

### Anything else?

An example command could be //waterflora or add it to the regular flora command and it detects whether on land or water

**Comment by dordsor21** [comment] 2022-08-25 17:04
duplicate of #650

**Closed by dordsor21** 2022-08-25 17:04 UTC
Labels: Enhancement
