### ISSUE TITLE
if config clipboard.use-disk is true, the clipboard brush breaks once the players active clipboard changes

### ISSUE THREAD

**Issue by eztaK-red** [IntellectualSites/FastAsyncWorldEdit#2984] opened 2024-11-10 01:58 UTC
### Server Implementation

Paper

### Server Version

1.21

### Describe the bug

When the config option `clipboard.use-disk` is set to `true`, a registered clipboard brush fails to continue to work if the active clipboard changes.

### To Reproduce

1. Select something and do //copy
2. //brush clipboard
3. Select something else and do //copy again
4. Try to use the brush (it fails)

### Expected behaviour

The brush should still continue to work, even if the players active clipboard changes, as it does with `clipboard.use-disk: false`.

### Error log (if applicable)

https://paste.gg/p/anonymous/2c0ff208f3594fdbbd99aab10a4aad3d

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/171c8a6b7acf429cbe1406bb93c8ef6c

### Fawe Version

#961

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by dordsor21** [comment] 2024-11-10 09:38
Duplicate of #1864

**Closed by dordsor21** 2024-11-10 09:38 UTC
Labels: Requires Testing
