### ISSUE TITLE
Clipboard/History/Sessions data causing FAWE to react slowly in a certain dimension (most likely history)

### ISSUE THREAD

**Issue by LaurenceBarnes** [IntellectualSites/FastAsyncWorldEdit#887] opened 2021-01-28 22:40 UTC
Based on issue #855 

**/fawe debugpaste**: NOTE: Issues #855 and #881 also have debugpastes from the very same server

current debugpaste from the **Paper** Server (where the delay issue still occurs and the history/sessions/clipboard **data is not deleted**: https://athion.net/ISPaster/paste/view/11131ce6d6e84d678abb01c56305530a

current debugpaste from the **Tuinity** Server (server software doesn't play a role in this case, read below) where the history/etc **data IS deleted** and everything works fine again: https://athion.net/ISPaster/paste/view/bec29fe1d1bb4cb481b616d1ea6515da

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`): 559-585    
- Spigot/Paper Version Number (`/version`): 325-446, also Tuinity 183  
- Minecraft Version: 1.16.5

**Describe the bug**
Two weeks ago, in one dimension, we call it TerraformTest, FAWE had a minimum delay of 2.5+ seconds. Well, we solved it by copying all that progress to our main world dimension, which we were planning to do anyway.

Well, now about two weeks later, that issue doesn't happen on TerraformTest anymore, but on the main world, with a 1 second Minimum delay. 
Fun thing: we moved (cut+paste) the exact same world to another server test environment and all the core plugins (including FAWE), and there was no delay.
We copied it back to the main server environment and after starting, the issue still occured. Although it is a copy of the very same world that had and then didn't have the issue.
Now we made a copy of that world in the main server environment, simply named worldKopie, and after loading it, the issue didn't occur in worldKopie, but continued to appear in world.

Then we deleted world, and renamed worldKopie to world.

The delay issue happened again.

EDIT: We then moved our whole server then to a fresh Tuinity setup, the issue also occured there (we copied over all plugin data, as well as configs and of course, the worlds)

So after testing out a lot of possibilities by starting with using the configs (paper, spigot, bukkit) from the test environment for the main server, I found out something. We already had an idea that it may be something  clogging memory or the I/O thread (got the hint from the myWorlds dev as we first asked whether it could be it, he then recommended Tuinity because it could have also been the lighting engine clogging up), so I looked into the FAWE folder and found out that it is saving a bunch of data per dimension. Hence I just moved in the FAWE folder from the test environment where everything was working fine, and the issue was fixed.

**To Reproduce**
1. Use FAWE for a long while, it will obviously create many "history" files
2. At some point, it will cause FAWE to work slowly and have a minimum time that it needs to do stuff
3. Remove all those files 
4. It will work flawlessly again
5. Extra: If you don't work in this dimension anymore for a while (>1-2 weeks), it will stop happening and work perfectly again (probably because it doesn't create more history files?)

Of course, ask me if you need more info!

**Plugins being used on the server**
See in quoted issue

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.5](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by LaurenceBarnes** [comment] 2021-01-28 23:19
that fork creation was an accident lol

**Comment by MattBDev** [comment] 2021-01-29 00:37
We need a debug paste link to proceed with this issue. If we don't get one in the next 48 hours I will close this issue.

**Comment by LaurenceBarnes** [comment] 2021-01-29 00:41
I can provide you one of course (in a few hours, it is very late), but except for the fawe and Tuinity versions, as well as some plugin updates, nothing has really changed and I isolated the problem pretty much :D
Will do though!

**Comment by LaurenceBarnes** [comment] 2021-01-29 10:20
> We need a debug paste link to proceed with this issue. If we don't get one in the next 48 hours I will close this issue.

I added the debugpastes, check out the other debugpastes from my linked previous issues as well if that matters :D

**Comment by CatEricka** [comment] 2021-02-12 06:00
I know the problem.

The code related to history is here:

https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/20304bf7ade9522c132e141a48bd1e9fc56ab669/worldedit-core/src/main/java/com/boydti/fawe/object/changeset/DiskStorageHistory.java#L70-L71

and:

https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/20304bf7ade9522c132e141a48bd1e9fc56ab669/worldedit-core/src/main/java/com/boydti/fawe/util/MainUtil.java#L201-L220

Note here:

https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/20304bf7ade9522c132e141a48bd1e9fc56ab669/worldedit-core/src/main/java/com/boydti/fawe/util/MainUtil.java#L203


This method (`java.io.File::listFiles`) will access all files in the directory, when the number of files is very large, it will cause serious performance problems.

(https://stackoverflow.com/questions/50087949/is-there-a-better-alternative-to-file-listfiles-method)

**Comment by CatEricka** [comment] 2021-02-12 06:02
Of course, it is also feasible to clean up the history records regularly, but I don’t know if there is a way to safely delete old history records while the server is running.

**Comment by LaurenceBarnes** [comment] 2021-02-12 08:27
Thanks a lot for that additional info, I hope that'll help the devs fixing it.
I don't think it should be deleted while the server is running though, at least I wouldn't risk it. There is a workaround at least.
But it is fixable then?

**Comment by CatEricka** [comment] 2021-02-12 09:04
I think there are some feasible solutions. For example, use `java.nio.file` instead of `java.io`, maybe a 10x performance improvement (just guess); or cache the result of `MainUtil::getMaxFileId `; or use a database to store history.

The key to the issue is that it seems that fawe does not limit the number of history records, and the history records that grow during runtime will not be cleared.

Anyway, this requires some trade-offs.

**Comment by LaurenceBarnes** [comment] 2021-03-12 11:12
since @CatEricka provided some detailed solutions, is there a chance you could solve this @MattBDev ?
This issue is encountered quite often when doing a lot of work with brushes, as history files bunch up rather quickly.

**Closed** 2021-04-13 14:55 UTC
Labels: Approved, Performance
