### ISSUE TITLE
Millions of NullPointerExceptions in logs after seemingly using //paste

### ISSUE THREAD

**Issue by MrJoshuaT** [IntellectualSites/FastAsyncWorldEdit#2125] opened 2023-03-01 13:58 UTC
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

There are not too many details that be provided, the errors seem to be thrown when multiple `//paste` operations were executed. FAWE after doing lots of heavy operations suddenly started logging over 6+ million lines of warning and errors. In the error log, at line `4794` I've omitted `6,459,164` of `NullPointerException` messages. Additionally in the logs I've tried to capture a load of the commands used from when the server booted up, excluding the starting log messages.

We have some builders on the server trying to strain it and see if it'll crash. The error seemed to occur once they moved to the 501x501 plots, so any operations seen would only be a max of 501*501*world height. 

Some server details:
The CPU sat at 1 thread while this testing was going on - 3600 CPU.
We have 16GB of RAM allocated.
Disk only used 672MB of 50GB allocated

### To Reproduce

Unknown if this will reproduce the error always. All selections would be a max of 501x501. It would seem to happen after a very large selection had 2 `//copy` commands executed then 2 `//paste`. The logs have a ton of information about the use of `//generate -c white (perlin(10,x,(y+64)/ridgedmulti(10,x,y,z,0.02,1),z,0.01,1,0)-0.5)* (cos(sqrt(x^2+z^2+y^2) * 0.5))`, then copying, using the brush clipboard, copying twice, pasting twice, then the errors occurred in mass.

### Expected behaviour

When an error occurs, don't spam the logs with errors. Especially making a 421MB log file with 6+ million lines of logs.

### Error log (if applicable)

https://mclo.gs/kamXVke

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/2d57b8649c9f4f8a90e7062a928b06d3

### Fawe Version

FastAsyncWorldEdit version 2.5.2;19ed349

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

I'm happy to ask the team any questions which would help elaborate anything I may of missed or would help

**Comment by dordsor21** [comment] 2023-03-03 23:45
I almost think this might be caused by `//copy` being called twice before paste (close is not synchronised :)) )

**Comment by dordsor21** [comment] 2023-03-25 13:10
Actually a duplicate of #1864

**Closed by dordsor21** 2023-03-25 13:10 UTC
Labels: Requires Testing
