### ISSUE TITLE
Blockstate update command (for fences)

### ISSUE THREAD

**Issue by VL4DST3R** [IntellectualSites/FastAsyncWorldEdit#815] opened 2020-12-26 20:06 UTC
**Is your feature request related to a problem? Please describe.**
Yes. An issue i had with any async/chunk-based worldedit derivates (yours included) is that they don't update blocks when executing a command, so if you work with blocks that need their state updated, like fences, panes, water, etc. they won't. This leaves behind unconnected fences/panes (probably others), broken light* and floating water**.

*Light thankfuly has the `//fixlighting` command and does its job nicely, but there's no equivalent for placed blocks as far as i can tell.

**Same for water although not ideal, but this is questionable if its actually desired behavior or not, regardless, not the main issue.

**Describe the solution you'd like**
A `//blockupdate` command that refreshes every block inside a selection to its proper state, essentially like if you would break and place said block manually, which is incidentally how you have to do it currently if you want to fix this.

**Describe alternatives you've considered**
 I tried some bootleg ways to achieve this, turns out replacing air with chorus flowers causes them all to instantly break (causing horrible lag in the process) but this causes certain blocks to update and fixes bugged light. It sadly doesn't work for fences.

**Additional context**
This stuff is particularly bad with boats, as you can see:
![image](https://user-images.githubusercontent.com/32654378/103158431-7495c080-47c6-11eb-887b-ac4c56ac230d.png)

**Comment by N0tMyFaultOG** [comment] 2020-12-26 20:08
https://github.com/EngineHub/WorldEdit/pull/1623 fixes https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/815

**Comment by N0tMyFaultOG** [comment] 2020-12-26 20:08
Thx GitHub

**Comment by VL4DST3R** [comment] 2020-12-26 20:11
So when can we expect this to show up in the public plugin?

**Comment by N0tMyFaultOG** [comment] 2020-12-26 20:16
Once WorldEdit merges the PR and we merge upstream changes again.

**Comment by VL4DST3R** [comment] 2020-12-26 20:18
Any idea how long that usually takes? I'm new to following the dev side of those plugins.

**Comment by N0tMyFaultOG** [comment] 2020-12-26 20:26
Generally, there is no eta. We all do that in our spare time. So unless nobody raises a pull request to add those changes, you'll need to wait until someone has the time to.

**Comment by VL4DST3R** [comment] 2020-12-26 20:28
No problem, thank you for the info. Happy holidays!

**Comment by RedstoneFuture** [comment] 2020-12-27 01:29
Look at this: https://github.com/Brennian/Arceon-1.14/wiki/Experimental-tools .
(Not tested.)

**Comment by RedstoneFuture** [comment] 2020-12-27 01:32
https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/313

**Comment by NotMyFault** [comment] 2021-02-08 12:47
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/313

**Closed by NotMyFault** 2021-02-08 12:47 UTC
Labels: Enhancement
