### ISSUE TITLE
AsyncWorld

### ISSUE THREAD

**Issue by derverdox** [IntellectualSites/FastAsyncWorldEdit#381] opened 2020-03-28 15:01 UTC
Hey!
On the discord someone told me that AsyncWorld -> especially creating Worlds in an other thread is not working due to an exception caused by spigot -> WorldInitEvent may only be triggered synchronous.

Is there a way right now to create worlds async? Or do we have to find a workaround on our own?

Best regards?

Using 1.15

I am using the latest Version of FAWE (146)

**Comment by derverdox** [comment] 2020-03-28 15:02
I am using 1.15

**Comment by N0tMyFaultOG** [comment] 2020-12-17 10:31
No, bad stalebot.

**Comment by dordsor21** [comment] 2021-01-10 16:19
Duplicate of #299

**Closed by dordsor21** 2021-01-10 16:19 UTC
Labels: Enhancement
