### ISSUE TITLE
Unable to regenerate chunks

### ISSUE THREAD

**Issue by ThatPerkel** [IntellectualSites/FastAsyncWorldEdit#1232] opened 2021-08-18 06:34 UTC
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

In 90% of cases when I try to regenerate a few chunks, an error gets thrown into console (pasted below).

Before the error, it will regenerate few chunks, but definitely not all of them.

### To Reproduce

Regenerate any part of world.

### Expected behaviour

The area should be regenerated.

### Error log (if applicable)

https://gist.github.com/ThatPerkel/97f9eb1a2151d615c2b8e3f50dfef6eb

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/ae75f6189b6d493db0260fcb0b4ddbcf

### Fawe Version

version 1.17-157

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by NotMyFault** [comment] 2021-08-18 08:11
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1226

**Closed by NotMyFault** 2021-08-18 08:11 UTC
Labels: Invalid, Duplicate
