### ISSUE TITLE
FAWE becomes completely unresponsive when someone player leaves the server

### ISSUE THREAD

**Issue by Feniksovich** [IntellectualSites/FastAsyncWorldEdit#1955] opened 2022-09-23 13:44 UTC
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

When any player leaves the server FAWE stops responding to any commands for 1-2 minutes.
The bug appears irregularly, but quite often.

### To Reproduce

I couldn't find specific conditions to reproduce the bug.
To reproduce the bug, one player needs to leave the server, while the other would use some FAWE commands.

### Expected behaviour

FAWE shouldn't stop responding to commands after the player leaves the server.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/33875970/191974935-2c5a0c6e-17f2-4198-aabd-124f3fefd7d0.png)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/10b1cfec608846d4b8825685f0fc875e

### Fawe Version

FastAsyncWorldEdit version 2.4.5-SNAPSHOT-278

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

The bug is really annoying :c

**Comment by Feniksovich** [comment] 2022-09-23 13:46
I can provide any additional information upon request.

**Comment by dordsor21** [comment] 2022-10-08 12:22
Is this specific to commands run from the console, or does it include those run by players on the server? Does the player leaving have a large FAWE operation ongoing when the leave the server at all?

**Comment by Feniksovich** [comment] 2022-10-08 14:19
> Is this specific to commands run from the console, or does it include those run by players on the server?
Both cases affected, FAWE runs commands with a delay after player leaving.

> Does the player leaving have a large FAWE operation ongoing when the leave the server at all?
I suppose not. It is likely some players are actually leave of the server during operation process. But I don't think it's true for large operations only. Any suggestions on what large operation I should to run to test?

**Comment by Skygroz** [comment] 2022-11-26 18:13
Agree with Phoenix, this problem occurs when the player logs out of the server, and the plugin stops responding. If you do frequent re-login to the server, the plugin will not respond for a very long time 
I demand a fix for this !!! Building with a terribly bad plugin is inconvenient !!!!

**Comment by dordsor21** [comment] 2023-01-06 15:13
The output of /fawe threads would likely be very useful when this occurs

**Comment by Feniksovich** [comment] 2023-01-08 13:49
> The output of /fawe threads would likely be very useful when this occurs

The last time FAWE stuck until the server was restarted and didn't respond to its own commands.
So here is Spark profiler report: https://spark.lucko.me/E3CJi0eQdW (with --thread *).

**Comment by Feniksovich** [comment] 2023-01-12 14:35
> I believe this is caused by players leaving the server with large clipboard that need to be close/written to disk - effectively caused by #1493

It seems to be true. Some time ago I noticed the bug reproduces much less frequently after switching from HDD to SSD (I really forgot notice this here for some reason).

**Comment by OneLiteFeather** [comment] 2023-04-18 18:10
@dordsor21 Should this issue stay opened or can it be closed?

**Comment by PierreSchwang** [comment] 2023-04-18 18:46
Would need re-evaluation imo - not sure if the issue is really fixed

**Comment by dordsor21** [comment] 2023-04-18 19:02
I would leave it open for the moment

**Comment by Feniksovich** [comment] 2023-04-21 13:49
Issue still here but it appears less often than before.
--
2.6.0-SNAPSHOT-395

**Comment by dordsor21** [comment] 2023-06-11 10:39
Don't think this has been reported in a while by anyone, including on a server I know that had it relatively frequently. Gonna close but if someone still has the issue, can reopen

**Closed by dordsor21** 2023-06-11 10:39 UTC
Labels: Requires Testing
