### ISSUE TITLE
//undo //redo corrupts tile entities on 1.20

### ISSUE THREAD

**Issue by ViaBackwards** [IntellectualSites/FastAsyncWorldEdit#2296] opened 2023-06-15 01:25 UTC
### Server Implementation

Paper

### Server Version

1.20

### Describe the bug

When you copy and paste some tile entities, for example structure block, shulker boxes, and undo the shulkers go invisible, if you click them they reappear and the structure block has its nbt reset, there are no errors in console

### To Reproduce

copy and paste tile entities, run //undo and //redo, shulkers/chests should disappear, general strange behavior

### Expected behaviour

should work fine :) worked fine 1.19.4, something in 1.20 has borked it

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/5ef9d214fba01eebc66f3a030148c006

### Fawe Version

2.6.4-SNAPSHOT-480;79a2c14

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by OneLiteFeather** [comment] 2023-06-15 08:12
Somehow this debugpaste is empty, do you still have logs or can retry that? This also might be a duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/2287

**Comment by NotMyFault** [comment] 2023-06-15 08:15
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/2287

**Closed by NotMyFault** 2023-06-15 08:15 UTC
Labels: Requires Testing
