### ISSUE TITLE
Some selection modes are not working probably

### ISSUE THREAD

**Issue by lusu007** [IntellectualSites/FastAsyncWorldEdit#719] opened 2020-10-25 15:57 UTC
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**: https://athion.net/ISPaster/paste/view/09663b1503744a7cbc0295b94c0bf1a3

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`): 1.16-427;478ab16
- Spigot/Paper Version Number (`/version`): git-Paper-220  
- Minecraft Version: 1.16.3    

**Describe the bug**
``//sel polyhedral`` and ``//sel ellipsoid`` are not working correctly. 

``//sel polyhedral``: Polyhedral doesnt work but polyhedron works with the newest build.
``//sel ellipsoid``: The radius is not taken over correctly so the selection is smaller than it should be.

**To Reproduce**
Steps to reproduce the ``//sel polyhedral``:
//sel polyhedral
//pos1
//pos2 (and set at least 2 more points)
//set 1

Steps to reproduce the ``//sel ellipsoid``:
//sel ellipsoid
//pos1
//pos2 (for x,y,z)
//set 1

**Plugins being used on the server**
Arceon, Builders-Utilities, BungeeTabListPlus, Essentials, (WorldEdit)FastAsyncWorldEdit, goBrush, goPaint, HeadDatabase*, Hyperverse, LegendEssentials, LegendSchematicScatter, LuckPerms, Vault, VoidGenerator, VoxelSniper, WorldGuard

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.3](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment] 2020-10-26 18:39
check this issue:
https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/393

**Comment by aurorasmiles** [comment] 2020-11-21 20:15
Duplicate of #393

**Closed by aurorasmiles** 2020-11-21 20:15 UTC
Labels: Requires Testing
