### ISSUE TITLE
Error while loading

### ISSUE THREAD

**Issue by NONPLAYT** [IntellectualSites/FastAsyncWorldEdit#1392] opened 2021-11-02 14:35 UTC
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

when the server is started i get this error:
```[17:25:39 INFO]: [FastAsyncWorldEdit] Enabling FastAsyncWorldEdit v1.17-380;ee0d1b5
[17:25:39 WARN]: [com.fastasyncworldedit.core.configuration.Config] Invalid config field: enabled-components.plotsquared-v4-hook for enabled-components
[17:25:39 ERROR]: [com.fastasyncworldedit.core.configuration.Config] Failed to set config option: enabled-components.plotsquared-v4-hook: true | com.fastasyncworldedit.core.configuration.Settings$ENABLED_COMPONENTS@34c71e80 | Settings.yml
[17:25:39 INFO]: [com.fastasyncworldedit.core.Fawe] LZ4 Compression Binding loaded successfully
[17:25:39 INFO]: [com.fastasyncworldedit.core.Fawe] ZSTD Compression Binding loaded successfully```
How to disable plotsquared-v4-hook?

And one more bug, when the server just works, the person rejoin the server, wand does not work and there is no message about successful filling. In console no messages about error

### To Reproduce

1. Starting server
2. Wait when FAWE is statring
3. See error

Second bug:
1. Join the server
2. Wait 15 minutes
3. See error (wand and messages not work)

### Expected behaviour

I was waiting for a successful fill message

### Screenshots / Videos

_No response_

### Error log (if applicable)

_No response_

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/e30cc5d2e21842bd9abbd7db9598141b

### Fawe Version

FastAsyncWorldEdit-1.17-380

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

### Anything else?

_No response_

**Comment by NotMyFault** [comment] 2021-11-02 14:37
Duplicate of #1372

**Closed by NotMyFault** 2021-11-02 14:37 UTC
Labels: Requires Testing, Invalid
