### ISSUE TITLE
Lighting Error when pasting Schematic and //fixlighting not working.

### ISSUE THREAD

**Issue by SirCraftypants** [IntellectualSites/FastAsyncWorldEdit#510] opened 2020-06-15 09:20 UTC
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

Config.yml   https://www.dropbox.com/s/egeaa4c2nieknn3/config.yml?dl=0
Config-Legacy.yml   https://www.dropbox.com/s/lyk9umopx57kv6s/config-legacy.yml?dl=0
Schematic    https://www.dropbox.com/s/hy1evbwdoknija1/mountainenclosure.schem?dl=0

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
version 1.15.2  256

**[REQUIRED] Spigot/Paper Version Number:** 
running Paper version git-Paper-334 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**[REQUIRED] Description of the problem:**

When I paste in a large Schematic Server side, almost the entire build is covered in shadow. I'm pasting it between 2 to 5 blocks above the lowest build level.

I've undone and pasted 8 times and always the exact same happens, there are no lighting blocks present, only dirt, grass_block, stone, cobblestone and andesite.

Photo to show issue.
https://imgur.com/zDZSTKh

I've tried //fixlighting but it's not working, I've tried lightcleaner but that doesn't work either so not an option, i've also tried Paper fixlight but that is not working either so again not an option.

Here is the log for the //fixlighting error
https://paste.helpch.at/ebexiqocuq.bash

I just updated to Fawe 260 and attempted it again and can confirm still the same problem.

**How to replicate**:

Create a 275x275 Sq and 170 high hollow mountain, paste into a Void world, move out of render range and then return to the build and you should see that it's covered in shadow.

**Plugins being used on the server:**

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by SirCraftypants** [comment] 2020-06-15 21:25
Shadows also occurring while building using the Brush tool with large builds.

**Comment by SirCraftypants** [comment] 2020-06-16 08:35
I did a Server restart and attempted //fixlighting and it worked, seems like a block update issue may be?

**Comment by Nightwielder1** [comment] 2020-06-28 19:21
I am having this //fixlighting issue as well (latest build of PaperMC 1.15.2). For me, both FAWE's //fixlighting and the cleanlight plugin is broken. 

I talked to the devs of cleanlight and they seem to think both issues are caused by an issue with Paper's API.

**Comment by SirCraftypants** [comment] 2020-06-28 19:25
> 
> 
> I am having this //fixlighting issue as well (latest build of PaperMC 1.15.2). For me, both FAWE's //fixlighting and the cleanlight plugin is broken.
> 
> I talked to the devs of cleanlight and they seem to think both issues are caused by an issue with Paper's API.

Hi, the current solution to this problem is to, every time //fixlighting fails, restart your server and it will work again. along with //fixlighting, you can use /paper fixlight   

You will need the Bukkit Paper Permission to use /Paper Fixlight 

Which is:   bukkit.command.paper.*

**Comment by dordsor21** [comment] 2020-06-28 21:22
duplicate of #496

**Closed by dordsor21** 2020-06-28 21:22 UTC
Labels: Requires Testing, [!] Bug
