### ISSUE TITLE
Error with fixlighting

### ISSUE THREAD

**Issue by MysticCity** [IntellectualSites/FastAsyncWorldEdit#335] opened 2020-02-03 15:24 UTC
Server: 
Paper 1.14.4

Plugin:
1.15-58

Error:
03.02.2020 16:21:03 [INFO] MysticCity issued server command: //fixlighting
03.02.2020 16:21:04 [SEVERE] An unexpected error while handling a WorldEdit command
03.02.2020 16:21:04 java.lang.UnsupportedOperationException: Queue is not interface com.boydti.fawe.object.extent.LightingExtent
03.02.2020 16:21:04 	at com.boydti.fawe.FaweAPI.fixLighting(FaweAPI.java:435) ~[?:?]
03.02.2020 16:21:04 	at com.sk89q.worldedit.command.RegionCommands.fixLighting(RegionCommands.java:155) ~[?:?]
03.02.2020 16:21:04 	at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_fixlighting(RegionCommandsRegistration.java:625) ~[?:?]
03.02.2020 16:21:04 	at org.enginehub.piston.CommandManager.execute(CommandManager.java:158) ~[?:?]
03.02.2020 16:21:04 	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$17(PlatformCommandManager.java:693) ~[?:?]
03.02.2020 16:21:04 	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:709) ~[?:?]
03.02.2020 16:21:04 	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:695) ~[?:?]
03.02.2020 16:21:04 	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$15(PlatformCommandManager.java:665) ~[?:?]
03.02.2020 16:21:04 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-231]
03.02.2020 16:21:04 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-231]
03.02.2020 16:21:04 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-231]
03.02.2020 16:21:04 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_231]
03.02.2020 16:21:04 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_231]
03.02.2020 16:21:04 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]

**Comment by N0tMyFaultOG** [comment] 2020-02-03 15:26
Duplicate of #333

**Closed by N0tMyFaultOG** 2020-02-03 15:26 UTC
Labels: [✖] Duplicate
