### ISSUE TITLE
FAWE undo of entities does not work (Armor stand)

### ISSUE THREAD

**Issue by AmberstoneDream** [IntellectualSites/FastAsyncWorldEdit#1022] opened 2021-04-10 12:26 UTC
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

After copying and pasting with //copy -e and //paste -e a selection including Armor stand, by undoing the blocks are removed but not the armor stand

### To Reproduce

//copy -e selection with armor stand
//paste -e 
and /undo

### Expected behaviour

Armor stand doesn't remove after /undo command

### Error log (if applicable)

no error appear on the console

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/6c7b4363fd8a4c8281a7d555221cc882

### Fawe Version

1.16-655;88764b8

### Checklist

I have included a Fawe debugpaste.
I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by NotMyFault** [comment] 2021-04-22 22:05
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/676

**Closed by NotMyFault** 2021-04-22 22:05 UTC
Labels: Approved, Bug
