### ISSUE TITLE
add support Folia 1.21

### ISSUE THREAD

**Issue by wundertraume** [IntellectualSites/FastAsyncWorldEdit#3034] opened 2024-12-19 21:57 UTC
### What feature do you want to see added?

add support Folia 1.21

### Are there any alternatives?

add support Folia 1.21

**Comment by dordsor21** [comment] 2024-12-31 16:00
Effective duplicate of #2297 

I would also prefer a locked issue given people were/are obnoxiously prickish about Folia support across GitHub, Discord, and even spamming harassing Spigot reviews.

**Closed by dordsor21** 2024-12-31 16:00 UTC
Labels: Enhancement
