### ISSUE TITLE
Degree mask /[Mind][Maxd] is bugged below y=0

### ISSUE THREAD

**Issue by Idan27I** [IntellectualSites/FastAsyncWorldEdit#1683] opened 2022-04-01 16:04 UTC
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

Using the degree mask below y=0 creates weird lines in the terrain.

### To Reproduce

1. Create a simple terrain
2. Select the whole terrain
3. /gmask [0d][40d]
4. //replace ID ID 

All of that, below y=0

### Expected behaviour

Before 1.18, the command was just fine replacing the degrees without lefting weird lines

### Screenshots / Videos

![Screenshot_1](https://user-images.githubusercontent.com/34960120/161300294-360761e6-06d8-4261-a8c2-e2df1080682b.png)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/b8a5d60f71464aeaa9fde8cdf4b2c2fd

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-139.jar

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

To be honest, a lot of other features are affected by the -y problem, including //fillr for example where the issue is this one:
![unknown](https://user-images.githubusercontent.com/34960120/161300633-3e9827a5-043d-444c-b9bc-9980cb44d9e9.png)

**Comment by DoTrONoL** [comment] 2022-04-12 19:28
Still broke

**Comment by DoTrONoL** [comment] 2022-04-12 20:24
Still broke. I was testing some outdated versions, ver 135 doesn't have this bug but it only works for 1.18.1 and below server. 1.18.2 need ver 136+

I also tested ver 153 and it has the same issue as the image above.

**Comment by dordsor21** [comment] 2022-04-21 23:00
Duplicate of #1664 (also not an issue based on y-coord)

**Closed by dordsor21** 2022-04-21 23:00 UTC
Labels: Requires Testing
