### ISSUE TITLE
TAGS PATTERN NOT WORKING on any server (including Builder's Refuge)

### ISSUE THREAD

**Issue by IIIagoC** [IntellectualSites/FastAsyncWorldEdit#1673] opened 2022-03-22 07:42 UTC
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

![Screenshot_782](https://user-images.githubusercontent.com/74384748/159428021-8289f469-0183-45a7-8b51-50a825b39244.png)

FAWE dont work properly when **Tag patterns** are used on mask camps. For some reason it always says "_Too many arguments_" or "_Unknown mask_"
Here's a screenshot from the WE wiki, explaining how tags should work

![Screenshot_783](https://user-images.githubusercontent.com/74384748/159428261-e29a82b3-28a1-494c-892a-dacae27c67f7.png)

ps: that error just occurs with **Tag patterns**. **Type patterns** works fine, altho they were both added at the same version of we

### To Reproduce

using a region with random wools, type

//replace ##wool stone

### Expected behaviour

All wools are supposed to be replaced for stone, independently of it's color

![2022-03-22_04 35 25](https://user-images.githubusercontent.com/74384748/159430540-86c38d05-8f9c-4307-a8ab-e339686336cb.png)
![2022-03-22_04 35 41](https://user-images.githubusercontent.com/74384748/159430546-343729f5-2910-41ee-bbc0-6434082a4024.png)
 
^ (Illustrative images, since the command doest work... thats how it SHOULD work)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/640b133fecc242749cf6e72647cd8c03

### Fawe Version

FastAsyncWorldEdit-2.1.1-SNAPSHOT-134

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by SirYwell** [comment] 2022-03-22 07:45
duplicate of #1532

**Closed by SirYwell** 2022-03-22 07:45 UTC
Labels: Requires Testing
