### ISSUE TITLE
Message output malformed

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/FastAsyncWorldEdit#1080] opened 2021-05-17 19:02 UTC
Currently Fawe mangles the output of text components used by plugins such as WorldGuard.

![](https://i.imgur.com/efVGIlB.png)

**Comment by aurorasmiles** [comment] 2021-05-17 19:09
Duplicate of #756 
😘

**Closed by aurorasmiles** 2021-05-17 19:09 UTC
Labels: Approved, Bug, Good first issue

**Comment by NotMyFault** [comment] 2021-05-17 19:12
Oh, I thought someone would've bothered the couple of minutes not maltreating stringified inputs.
