### ISSUE TITLE
[1.15.1] ArrayIndexOutOfBoundsException when pasting schematics/buildings

### ISSUE THREAD

**Issue by voodootje0** [IntellectualSites/FastAsyncWorldEdit#311] opened 2020-01-05 13:31 UTC
**[REQUIRED] FastAsyncWorldEdit Version Number:** 
&7FastAsyncWorldEdit-12 created by Empire92
&7FAWE version:
- Date Dec 23, 2019 12:00:00 AM
- Commit faf3e60b
- Build 12
- Platform bukkit
&7Wiki: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki
------------------ Platforms ------------------
* Bukkit-Official(1.15-12;50c19f5)
---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official

**[REQUIRED] Spigot/Paper Version Number:** 
git-Paper-27 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)

**[REQUIRED] Description of the problem:**
When you select and copy a large building (100x100 spawn with tons of different colored blocks), then you //cut it, than you to a new location (only a few blocks lower) and type //paste it will throw this error in console.
https://pastebin.com/jF9vmHzZ

You will get the same error when you are loading a schematic (100 x 100 spawn) and try to //paste it somewhere.

**How to replicate**:
Simply try pasting a larger kind of schematic/build and check your console for ArrayIndexOutOfBoundsExceptions.

**Plugins being used on the server:**

PlotSquared 4.433

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue) (There are similar issues, but not exactly about pasting)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by IronApollo** [comment] 2020-02-18 01:46
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/307, closed.

**Closed by IronApollo** 2020-02-18 01:46 UTC
Labels: Requires Testing
