### ISSUE TITLE
Invalid config field

### ISSUE THREAD

**Issue by srnyx** [IntellectualSites/FastAsyncWorldEdit#1400] opened 2021-11-06 17:21 UTC
### Server Implementation

Purpur

### Server Version

1.17.1

### Describe the bug

I'm getting a warning and an error on startup and on FAWE reload

### To Reproduce

1. Install FAWE
2. Start server

### Expected behaviour

No warnings/errors

### Error log

https://paste.srnyx.xyz/raw/serofuvuwe

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/cebf8fcf2b114ee0b18e53ed20f890e5

### Fawe Version

FastAsyncWorldEdit version 1.17-389;95ecb56

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by SirYwell** [comment] 2021-11-06 17:28
Duplicate of  #1372

**Closed by SirYwell** 2021-11-06 17:28 UTC
Labels: Requires Testing

**Comment by srnyx** [comment] 2021-11-06 17:32
> Duplicate of #1372

Sorry, I tried searching for it but couldn't find it, don't know how I missed it.
