### ISSUE TITLE
Schematic folders are not recognized within the #fullcopy pattern and an error is displayed multiple times

### ISSUE THREAD

**Issue by PhilippUlti** [IntellectualSites/FastAsyncWorldEdit#1247] opened 2021-08-24 09:51 UTC
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

There are two bugs within this issue report.
First of all the recognization of folders within the fullcopy pattern does not work. Only single schematic files are working.
The second bug is that a message (as you will see below) is written in the chat multiple times.
![2021-08-24_11 19 27](https://user-images.githubusercontent.com/69215640/130592413-a0c9dd5c-3d95-4bd8-83f4-8633e63bb977.png)

### To Reproduce

1. Save multiple or single schematics inside a folder (/schem save oaktree/01)
2. Bind a scatter brush to a tool of your choice (/br scatter #fullcopy[oaktree][true][true] 1 1 1 -o)
3. The chat is going to be filled with error messages saying the folder(schematic) does not exist
4. The brush is not recognized

### Expected behaviour

The fullcopy pattern should be able to recognize not only a singe schematic but also folder structures.
Besides that the error message that a schematic(-folder) does not exist should not be displayed in the chat that often (it is not even necessary to print this statement one time).

### Screenshots / Videos

![2021-08-24_11 19 27](https://user-images.githubusercontent.com/69215640/130594983-77a2453b-5e8a-4a9b-a638-59cefdbf31c7.png)

![2021-08-24_11 43 10](https://user-images.githubusercontent.com/69215640/130595105-0b2fc983-4ad2-4c3c-a30a-4978eaca1d7b.png)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/2c97639357f34dbb8fd1505294b649eb

### Fawe Version

FastAsyncWorldEdit version 1.17-176;7d9abc9

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by NotMyFault** [comment] 2021-08-24 23:16
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/736

**Closed by NotMyFault** 2021-08-24 23:16 UTC
Labels: Duplicate
