### ISSUE TITLE
Tile entities turn invisible & loose their data

### ISSUE THREAD

**Issue by ItsaMeMarvino** [IntellectualSites/FastAsyncWorldEdit#2541] opened 2024-01-06 12:23 UTC
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

when you move a structure and its blocks somewhere and back again, tile entities turn invisible & loose their nbt data.
This includes the corruption of player heads, banners, signs and decorated pots.
the blocks are still there, they just turn invisible.
We have seen this bug since 1.19.4 and it really destroys a lot of work and progress in our projects.

### To Reproduce

0. The bug occurs rarely but when it does, the damage is big.

1.Select an area with time enities in it
2. move it
3. //undo to get it back to the original position
4. Bug should have occured now

### Expected behaviour

tile enties should not loose their data nor become invisible

### Screenshots / Videos

![bugged pot](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/94754321/5e5f227f-4e5b-4a5d-8209-83d467aeaad2)

![bugged heads](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/94754321/72dd303d-c76c-490f-befe-3218aa0df33b)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/c5454bfba70842b698d8506ed111dfee

### Fawe Version

FastAsyncWorldEdit version 2.8.5-SNAPSHOT

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

we are using the build version of a day ago

**Comment by Hunter99011** [comment] 2024-03-05 23:50
Upvote, I dont really get why no fixes in this direction happened in the past 2 months, after doing //paste -a the same issues happens, you cannot really undo the damage that it does to your world.

**Comment by OneLiteFeather** [comment] 2024-03-06 20:59
What about these datapacks? Do you have a fresh world without them and tried to replicate your tile entity issue?
` - file/Disable unnecessary vanilla features.zip
 - file/SBS Tools.zip
 - file/Dronentechnik.zip
 - file/Airhockey.zip`

**Comment by Hunter99011** [comment] 2024-03-06 21:47
The author might have datapacks, but we had the same issues with paste and undo without datapacks too.

It corrupted multiple regions. Without using datapacks.

**Comment by Timongcraft** [comment] 2024-03-07 04:54
> What about these datapacks? Do you have a fresh world without them and tried to replicate your tile entity issue? ` - file/Disable unnecessary vanilla features.zip
> 
> * file/SBS Tools.zip
> * file/Dronentechnik.zip
> * file/Airhockey.zip`

I'm working with @ItsaMeMarvino and I just tried it on the latest (git-Paper-446 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 6ad63fb)) paper and the latest (v2.9.1-SNAPSHOT-669;eca4dbd) fawe FAWE.
And it **appears** to be fixed.

**Comment by OneLiteFeather** [comment] 2024-03-07 08:36
I think it is fixed in newer paper and fawe versions too, we've not heard of it in a while, also there was a lot fixed in between. Didn't see any invisible entities on fawe anymore on testing

**Comment by ItsaMeMarvino** [comment] 2024-03-14 16:04
The bug has NOT been fixed yet. We have today found a new appearance of this bug.
![grafik](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/94754321/914a5f08-d89b-4f83-b1f5-04c2300baabd)

We are using the latest version of FAWE and Paper.

debug paste:
https://athion.net/ISPaster/paste/view/26aa294e66804be89a3a7aa4209c388b

**Comment by dordsor21** [comment] 2024-06-14 20:42
This is gonna be a duplicate of #1548

**Closed by dordsor21** 2024-06-14 20:42 UTC
Labels: Bug
