### ISSUE TITLE
//fixlightning causes NullPointerException

### ISSUE THREAD

**Issue by ignissak** [IntellectualSites/FastAsyncWorldEdit#522] opened 2020-06-29 19:15 UTC
**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/f0351cf97bf64f018fdc212a4f2b6ef1

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
Version 1.15, build 263

**[REQUIRED] Spigot/Paper Version Number:** 
`This server is running Purpur version git-Purpur-"c2c6a6e" (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)`

**[REQUIRED] Description of the problem:**
Executing //fixlightning causes and NullPointerException. 
```
[21:10:32 ERROR]: An unexpected error while handling a WorldEdit command
java.lang.NullPointerException: null
at com.boydti.fawe.bukkit.adapter.mc1_15_2.BukkitGetBlocks_1_15_2.getSkyLight(BukkitGetBlocks_1_15_2.java:146) ~[?:?]
at com.boydti.fawe.beta.implementation.chunk.ChunkHolder$2.getSkyLight(ChunkHolder.java:339) ~[?:?]
at com.boydti.fawe.beta.implementation.chunk.ChunkHolder.getSkyLight(ChunkHolder.java:819) ~[?:?]
at com.boydti.fawe.beta.implementation.lighting.NMSRelighter.smoothSkyLight(NMSRelighter.java:583) ~[?:?]
at com.boydti.fawe.beta.implementation.lighting.NMSRelighter.fixSkyLighting(NMSRelighter.java:514) ~[?:?]
at com.boydti.fawe.beta.implementation.lighting.NMSRelighter.fixSkyLighting(NMSRelighter.java:382) ~[?:?]
at com.boydti.fawe.FaweAPI.fixLighting(FaweAPI.java:413) ~[?:?]
at com.sk89q.worldedit.command.RegionCommands.fixLighting(RegionCommands.java:151) ~[?:?]
at com.sk89q.worldedit.command.RegionCommandsRegistration.cmd$_fixlighting(RegionCommandsRegistration.java:600) ~[?:?]
at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$15(PlatformCommandManager.java:679) ~[?:?]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:695) ~[?:?]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:681) ~[?:?]
at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$13(PlatformCommandManager.java:651) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[server.jar:git-Purpur-"c2c6a6e"]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[server.jar:git-Purpur-"c2c6a6e"]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[server.jar:git-Purpur-"c2c6a6e"]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

**How to replicate**:
Execute //fixlightning, anywhere.

**Comment by aurorasmiles** [comment] 2020-06-29 20:31
Duplicate of #496

**Closed** 2020-06-29 20:34 UTC
Labels: Requires Testing
