### ISSUE TITLE
Any worldedit operation causes rain to pass through blocks (even with after //fixlighting)

### ISSUE THREAD

**Issue by VL4DST3R** [IntellectualSites/FastAsyncWorldEdit#985] opened 2021-03-20 11:17 UTC
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

This is somewhat a rehash of #386, but with some further testing and more info that I've discovered about the issue as it is affecting more than i initially thought.

To reiterate the previous ticket: after pasting a building (or as far as i can tell: doing any operation affecting chunks) the chunks where the edit took place no longer display properly. Rain passes through roofs, light behaves as exposed to the sky and sometimes server chunks disappear completely for the client that made the edit (the actual operation completes successfully server-side)

The workaround provided in the aforementioned ticket suggests running `//fixlighting` after pasting. Problem is, it does not actually properly fix the issue; I attached a video that best describes the issue in action.

In the next section i provide the steps presented in the video to cause the results shown there.

### To Reproduce

1. Toggle rain and run any Paste/Replace operation on an area.
2. Notice that in the chunks where the edit took place rain starts passing through most of not all roofed areas (expected).
3. Run //fixlighting. While it does prevent the particles from clipping through the blocks, the game still considers that area as "exposed" or devoid of blocks. This can best be seen with any shader that provides a wetness overlay when raining.
4. Manually place (or, as i found out using `chorus_flower` to somewhat automate this process) then break blocks on the affected area's "roof" to properly update that column of blocks. Do note that this needs to be done individually for each 1x128x1 area (column-by-column, starting from the roof).
5. Even in this "properly fixed" state, running `//fixlighting` by itself again causes the issue on 3.

### Expected behaviour

Chunks to be properly updated whenever an edit takes place so that oddities like this don't occur.

### Screenshots / Videos

https://www.dropbox.com/s/gctqay1vaz2a00l/paste-rain-fixlighting-blockupdate.mp4?dl=0

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/f21ed878cc154e5b9c99f3d016cc190e

### Fawe Version

FastAsyncWorldEdit version 1.16-626;d224d6e

**Comment by LaurenceBarnes** [comment] 2021-03-20 11:35
Related to #881 and #891

**Comment by MattBDev** [comment] 2021-03-20 21:36
Duplicate of #881 and #891

**Closed by MattBDev** 2021-03-20 21:36 UTC
Labels: Requires Testing
