### ISSUE TITLE
FastAsyncWorldEdit v1.16-602;e3ab903: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by ylluminate** [IntellectualSites/FastAsyncWorldEdit#917] opened 2021-02-16 01:08 UTC
Running git-Paper-468 (MC: 1.16.5) and got the following warning:
```
> WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.boydti.fawe.util.ReflectionUtils (file:/home/minecraft/paper/plugins/FastAsyncWorldEdit-1.16-602.jar) to field java.lang.Enum.ordinal
WARNING: Please consider reporting this to the maintainers of com.boydti.fawe.util.ReflectionUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
Full log: https://mclo.gs/O3Qo0rA

**Comment by LaurenceBarnes** [comment] 2021-02-16 07:24
Is it that hard to keep the format?

**Comment by SirYwell** [comment] 2021-02-16 07:45
Duplicate of #396

**Closed by SirYwell** 2021-02-16 07:45 UTC
Labels: Requires Testing
