### ISSUE TITLE
wand command not work

### ISSUE THREAD

**Issue by LowScarlet** [IntellectualSites/FastAsyncWorldEdit#1158] opened 2021-06-30 12:30 UTC
### Server Implementation

Paper

### Server Version

1.17.+

### Describe the bug

Wand command not work

### To Reproduce

1. join to server
2. use command //wand

### Expected behaviour

give wand item and enable to set pos1 pos2

### Screenshots / Videos

no

### Error log (if applicable)

https://gist.github.com/LowScarlet/9f63e5298aafa1f5cf83676ed95a26d0

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/b9af6857baa04d9788f37ccd71849283

### Fawe Version

FastAsyncWorldEdit version 1.17-22;6f1ffc6

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ or an experimental build and the issue still persists.

**Comment by NotMyFault** [comment] 2021-06-30 12:56
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1148

**Closed by NotMyFault** 2021-06-30 12:56 UTC
Labels: Duplicate
