### ISSUE TITLE
Illegal reflective access by com.boydti.fawe.object.collection.CleanableThreadLocal (file:/data/plugins/FastAsyncWorldEdit-Bukkit-1.16-666.jar) to field java.lang.Thread.threadLocals

### ISSUE THREAD

**Issue by almandoro** [IntellectualSites/FastAsyncWorldEdit#1035] opened 2021-04-23 15:21 UTC
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

Hello, 

After server loads ( PaperMC 1.16.5 ) I see this error in console from FAWE:

>....WARNING: An illegal reflective access operation has occurred
--
  | WARNING: Illegal reflective access by com.boydti.fawe.object.collection.CleanableThreadLocal (file:/data/plugins/FastAsyncWorldEdit-Bukkit-1.16-666.jar) to field java.lang.Thread.threadLocals
  | WARNING: **Please consider reporting this to the maintainers of com.boydti.fawe.object.collection.CleanableThreadLocal**
  | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
  | WARNING: All illegal access operations will be denied in a future release
  | [15:15:44 INFO]: Higher left the game

### To Reproduce

Download latest FAWE and launch 1.16.5 server.

### Expected behaviour

No error in console

### Error log (if applicable)

https://paste.gg/p/anonymous/db18763b53c842b6865a605d24fa3188

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/df5930d6f14d40c2968d431890fbbbf3

### Fawe Version

FastAsyncWorldEdit version 1.16-666;ceacd7b

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by NotMyFault** [comment] 2021-04-23 15:23
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/396.
Report illegal reflective operations here.

**Closed by NotMyFault** 2021-04-23 15:23 UTC
Labels: Requires Testing
