### ISSUE TITLE
Get rid of the sun.misc imports in ReflectionUtil (worldedit-core)

### ISSUE THREAD

**Issue by yannicklamprecht** [IntellectualSites/FastAsyncWorldEdit#183] opened 2019-07-06 09:48 UTC
**Describe the solution you'd like**
I would like to get rid of the sun.misc imports. 

**Describe alternatives you've considered**
Using ByteBuddy and/or imports that are not removed in later versions of Java.

**Comment by SirYwell** [comment] 2019-07-06 20:51
We‘re aware of the incompatibility. For now, other problems have a higher priority, but I‘ll try to find some time to take a look at it.

**Comment by MattBDev** [comment] 2019-07-06 21:36
This is extremely low on the todo list.

**Comment by MattBDev** [comment] 2020-02-06 19:23
I would like to note that progress has been made on this issue.

**Comment by NotMyFault** [comment] 2021-04-12 11:40
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/396
Yet this is the older version, however, we've got reflections and other methods under 396.

**Closed by NotMyFault** 2021-04-12 11:40 UTC
Labels: Enhancement, Low Priority
