### ISSUE TITLE
Stairs orientation breaks when rotating 90° (and consequently, 270°)

### ISSUE THREAD

**Issue by LaurenceBarnes** [IntellectualSites/FastAsyncWorldEdit#1175] opened 2021-07-10 17:03 UTC
### Server Implementation

Purpur

### Server Version

1.16.5

### Describe the bug

See on the screenshot:
object highlighted is the original,
above //rotate 180 (completely fine)
on top it is with //rotate 90 (with wrongly rotated stairs)

![2021-07-10_18 57 20](https://user-images.githubusercontent.com/77249464/125170801-0d16ef80-e1b1-11eb-8d90-679ee4938caa.png)

### To Reproduce

1. copy a selection with stairs
2. //rotate 90
3. //paste
4. boom

### Expected behaviour

stairs rotate correctly

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/3ea7333d27ca47d48e3cde854644b261

### Fawe Version

FAWE-1.17-48

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

### Anything else?

It's a Sith legend. Darth Plagueis was a Dark Lord of the Sith, so powerful and so wise he could use the Force to influence the midichlorians to create life…

**Comment by dordsor21** [comment] 2021-07-10 18:45
Duplicate of #1162

**Closed by dordsor21** 2021-07-10 18:45 UTC
Labels: Requires Testing
