### ISSUE TITLE
Certain chunk section light glitch related to how FAWE creates chunk sections

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#497] opened 2020-06-01 02:04 UTC
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
config.yml: https://pastebin.com/qbx642wn
config-legacy.yml: https://pastebin.com/E4qmuBMb

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
FastAsyncWorldEdit-1.15-256

**[REQUIRED] Spigot/Paper Version Number:** 
git-Paper-301 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**[REQUIRED] Description of the problem:**
When using FAWE for tall set operations some of the chunk sections in between the selection will have very strange behavior in regards to lighting (the 3rd chunk section from my testing for some reason), you won't be able to see the glitch but relogging after the operation will make the glitch visible and multiple relogs may show the glitch looking different each time. If you don't want to relog you can also move away from the chunk to make it unload and load it again to make the glitch visible. In this state you cannot use //fixlight or /cleanlight to fix the glitch - it's as if something is stuck. The only way to fix this is to restart the server and then run //fixlight or /cleanlight. 

This isn't a normal lighting glitch though, it's very specific and shouldn't be happening in the first place since FAWE does not touch lighting at all. This only affects certain chunk sections in between the region selection. The issue is related to the way FAWE is either creating the chunk sections or setting the blocks, even if the set operation handled lighting updates this glitch would still occur. I believe it has something to do with the chunk sections in between the region selection having no data, only the bottom and the top chunk section used for the region selection positions had data associated to them because a block had been placed in them so that I could select the region. I confirmed this because I was unable to reproduce this glitch when every chunk section in the region selection had a block placed in it. 

I have explained this issue more thoroughly in the "How to replicate" section with screenshots.

This is what the issue causes: https://gfycat.com/deadlyadeptegg

**How to replicate**:
Make sure to not use shortcuts such as //up or //pos2 during this test, they will not cause the glitch to occur. I was only able to pin this issue down after a lot of precise testing based on certain conditions.

Using a new world place a block in the corner of a chunk section:
![image](https://user-images.githubusercontent.com/10485646/83366944-00b74500-a3aa-11ea-82d0-5a48f7694bc9.png)

On the opposite corner build a pillar **outside** of the chunk section until you have filled in the **5th chunk section**. This pillar needs to be built for the test so that you can place the second region position inside the same chunk as the first block you placed. The region you will be setting needs to have empty chunk sections in between the top and bottom for the glitch to happen.:
![image](https://user-images.githubusercontent.com/10485646/83367108-b84c5700-a3aa-11ea-9d46-9f4273273062.png)

Now use the pillar to place the block inside the chunk section you will be using for the set operation.
![image](https://user-images.githubusercontent.com/10485646/83367212-5b9d6c00-a3ab-11ea-9b25-9095f879a04a.png)

Select the first block you placed on the corner of the chunk section:
![image](https://user-images.githubusercontent.com/10485646/83367337-f5fdaf80-a3ab-11ea-9443-524806464636.png)

Now select the second block you placed on the opposite corner of the chunk
![image](https://user-images.githubusercontent.com/10485646/83367361-13327e00-a3ac-11ea-9097-a2070b99f82c.png)

Everything looks fine visually at first:
![image](https://user-images.githubusercontent.com/10485646/83367399-39581e00-a3ac-11ea-8ce4-f1f90dc4dfe5.png)

Rejoining or causing the chunk to unload and be loaded again will show that the **3rd chunk section** has a lighting glitch on at least one side:
![image](https://user-images.githubusercontent.com/10485646/83367465-8c31d580-a3ac-11ea-8c40-1b1c3034f51f.png)

Rejoining again will also show how something is going on behind the scenes to cause the glitch to look different:
![image](https://user-images.githubusercontent.com/10485646/83367723-de272b00-a3ad-11ea-823d-54dbaf469e8a.png)

It's also strange because it causes surrounding chunk sections that were not part of the region selection to also have a lighting glitch:
![image](https://user-images.githubusercontent.com/10485646/83367523-e16de700-a3ac-11ea-8481-9f31ff945879.png)

![image](https://user-images.githubusercontent.com/10485646/83367544-f9456b00-a3ac-11ea-886e-d0e8e8ca89cf.png)

Using //fixlight doesn't fix the glitch in this state:
![image](https://user-images.githubusercontent.com/10485646/83367835-702f3380-a3ae-11ea-9118-ee538c40b0e6.png)

You have to restart the server and then run //fixlight to fix the glitch.
![image](https://user-images.githubusercontent.com/10485646/83367898-bab0b000-a3ae-11ea-9560-7f58d79f0d84.png)

**Using //up will not cause this glitch for some reason:**
What's also strange is that instead of building a pillar to place the block in the chunk I tried using //up 79 and then used the block it placed as the second position for the set operation and it doesn't cause this glitch to happen. I'm not sure why the behavior is different when you use //up 79, it might be creating data for each chunk section even if it is not being touched.

**Plugins being used on the server:**
FastAsyncWorldEdit, LuckPerms, PlotSquared

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment] 2020-06-01 17:16
Thanks for the well detailed report. ♥️

**Comment by dordsor21** [comment] 2020-06-02 10:08
Is there any difference when using //removelight and then //fixlighting?

**Comment by SecretlyJealous** [comment] 2020-06-02 13:15
> Is there any difference when using //removelight and then //fixlighting?

Same behaviour when using //removelight and //fixlighting, nothing changes:
![image](https://user-images.githubusercontent.com/10485646/83524291-4de70400-a4db-11ea-8194-89f02303423e.png)

Relogging doesn't change anything either, you have to restart the server and then use the //fixlighting command to fix the glitch.

**Comment by SecretlyJealous** [comment] 2020-06-30 12:58
Still an issue using (1.15-265;4ca19ac)
![2020-06-30_13 57 34](https://user-images.githubusercontent.com/10485646/86128744-aeb52c80-bad9-11ea-842b-ec537783d6df.png)

**Comment by dordsor21** [comment] 2020-06-30 13:00
I don't know what you're doing here, I cannot replicate this at all...

**Comment by SecretlyJealous** [comment] 2020-06-30 13:06
Place a block in the corner of the chunk section:
![image](https://user-images.githubusercontent.com/10485646/86129166-2daa6500-bada-11ea-9bcd-2dc212acd4bb.png)

On the opposite corner go outside of the chunk section and use /up 79
![image](https://user-images.githubusercontent.com/10485646/86129223-43b82580-bada-11ea-8240-fff00406a78a.png)

Then use that block to place a block inside the chunk section your about to edit
![image](https://user-images.githubusercontent.com/10485646/86129246-4ca8f700-bada-11ea-8cae-728f1c2d72be.png)

Doing a set stone will look normal:
![image](https://user-images.githubusercontent.com/10485646/86129273-56caf580-bada-11ea-9e70-656f1d7f604b.png)

When you relog you will see that certain chunk sections have glitched lighting and neighboring chunk sections also have the glitch:
![image](https://user-images.githubusercontent.com/10485646/86129292-5df20380-bada-11ea-89f0-580b462ecc4e.png)

paper.yml: https://mcpaste.io/60b52f60d62783d3
spigot.yml: https://mcpaste.io/e03d468b3a7a7fdb

**Comment by aurorasmiles** [comment] 2020-06-30 13:07
I was also able to replicate it

**Comment by dordsor21** [comment] 2020-06-30 13:24
Seems to me that the fix for this will come ultimately when lighting is added to queues and done automatically. A //fixlighting fixes the issue, and presumably, it's to do with the way MC/spigot/paper handles lighting when sending "new" chunk packets to players, and halfasses any lighting updates therewith.

Since a //fixlighting, and there are plans to implement the fixlighting stuff into the edit pipelines, I'll mark this as backburner

**Comment by SecretlyJealous** [comment] 2020-06-30 13:30
The issue is that even if you manually set the lighting for operations this glitch will still occur, I tried using the FAWE API along with the cleanlight API to on purpose set the skylight for all chunk sections to be 15 on every operation but this glitch still occurred. Even if FAWE handles lighting this problem won't go away, it will just be the next issue to deal with.

**Comment by dordsor21** [comment] 2020-06-30 13:58
Well, presumably that's only setting the skylight inside the operation. The issue is for surrounding chunks, not the chunk changed by the edit. I see no way FAWE is directly causing this issue, outside of it being the thing placing the blocks, and not technically telling the server they're there to update lighting slowly and poorly. A fixlighting on the surrounding chunks still fixes the issue.

**Comment by SecretlyJealous** [comment] 2020-06-30 14:06
I think it is related to setting blocks with nms in empty chunk sections in 1.14 and above. It is strange that neighboring chunk sections that have nothing to do with the operation are being affected. A fixlighting or any other plugin that fixes the lighting only works after you have restarted the server. I'll report the issue to paper to see if they can fix it because fixlighting should not require the server to restart for the lighting to be fixed, it should be immediate which I can't get to work:

![image](https://user-images.githubusercontent.com/10485646/86135866-466b4880-bae3-11ea-8475-5715c50dd45d.png)

**Comment by dordsor21** [comment] 2020-06-30 14:13
When I've replicated, the server hasn't needed a restart. Make sure you're definitely using the very latest FAWE as I've fixed a few other lighting issues where not all chunksections of lighting were being set properly. Don't report this to paper as they may chastise you for using FAWE a little, and it's not something that's "their fault" or that's up to them to fix.

**Comment by SecretlyJealous** [comment] 2020-06-30 14:29
I'm on the latest:
![image](https://user-images.githubusercontent.com/10485646/86138371-49b40380-bae6-11ea-8fcb-7b24a76f282b.png)

Fixlighting doesn't change anything:
![image](https://user-images.githubusercontent.com/10485646/86138415-589ab600-bae6-11ea-84ce-935201ff3c19.png)

Rejoining doesn't change anything:
![image](https://user-images.githubusercontent.com/10485646/86138457-6819ff00-bae6-11ea-9971-3935b7402281.png)

Even a restart this time didn't fix it:
![image](https://user-images.githubusercontent.com/10485646/86138542-867ffa80-bae6-11ea-8019-6f480eec1998.png)

**Comment by dordsor21** [comment] 2020-06-30 14:32
> Well, presumably that's only setting the skylight inside the operation. The issue is for surrounding chunks, not the chunk changed by the edit. I see no way FAWE is directly causing this issue, outside of it being the thing placing the blocks, and not technically telling the server they're there to update lighting slowly and poorly. A fixlighting on the surrounding chunks still fixes the issue.

_Surrounding chunks_ not the edited chunk.

**Comment by MattBDev** [comment] 2020-06-30 16:29
I ran into this issue only when the server was hanging due to debugging.

**Closed** 2020-09-14 17:39 UTC
Labels: Approved, Backburner
