### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by nexnux** [IntellectualSites/FastAsyncWorldEdit#1680] opened 2022-03-30 08:04 UTC
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

Not sure what is going on, but whenever i restart the server i get an error message related to this.

### To Reproduce

I simply just restarted the server!

### Expected behaviour

[10:01:12 ERROR]: Could not pass event WorldInitEvent to FastAsyncWorldEdit v2.1.1-SNAPSHOT-136;c45b14a
java.lang.NullPointerException: Cannot invoke "net.minecraft.core.Holder.a()" because "value" is null
        at net.minecraft.core.Registry$1.getId(Registry.java:522) ~[?:?]
        at net.minecraft.core.Registry$1.a(Registry.java:519) ~[?:?]
        at com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_18_R2.PaperweightFaweAdapter.getInternalBiomeId(PaperweightFaweAdapter.java:642) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-136.jar:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.setupBiomes(WorldEditPlugin.java:323) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-136.jar:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.setupWorldData(WorldEditPlugin.java:240) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-136.jar:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin$WorldInitListener.onWorldInit(WorldEditPlugin.java:634) ~[FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-136.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-267]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.MinecraftServer.initWorld(MinecraftServer.java:681) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-267]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/5c933805229c4670b1baf4cf3d099dc2

### Fawe Version

FastAsyncWorldEdit v2.1.1-SNAPSHOT-136;c45b14a

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment] 2022-03-30 08:05
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1665

**Closed by NotMyFault** 2022-03-30 08:05 UTC
Labels: Invalid
