### ISSUE TITLE
Unable to copy and paste entities

### ISSUE THREAD

**Issue by CarloDrift** [IntellectualSites/FastAsyncWorldEdit#378] opened 2020-03-27 11:17 UTC
**FastAsyncWorldEdit Configuration Files:** 
Default configuration.

**FastAsyncWorldEdit Version Number:** 
![image](https://user-images.githubusercontent.com/30211659/77750049-67735780-7023-11ea-9789-c84b9ca22e6e.png)

**Paper Version Number:** 
![image](https://user-images.githubusercontent.com/30211659/77750080-76f2a080-7023-11ea-8cfc-a72ecbb1a4e9.png)

**Description of the problem:**
It's impossible to copy and paste entities. I asked on Discord, nobody can do it in 1.15. There is no error in console when I try.

**How to replicate**:
Copy an area with entities such as armor stands for example and paste it onward.

**Plugins being used on the server:**
FastAsyncWorldEdit and ProtocolLib.

**Checklist**:
- [x] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)
- [X] I made sure the bug/error is not caused by any other plugin

I know there's already a post on this, but it's old and has never been processed. Despite the updates, the bug is still there. Thank you.

**Comment by aurorasmiles** [comment] 2020-03-27 16:46
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/303

**Comment by MattBDev** [comment] 2020-03-27 19:32
Duplicate of #303

**Closed by MattBDev** 2020-03-27 19:32 UTC
Labels: Requires Testing
