### ISSUE TITLE
Entities (Text Displays) are not copied along with schematic

### ISSUE THREAD

**Issue by TomTeDev** [IntellectualSites/FastAsyncWorldEdit#2911] opened 2024-09-12 22:41 UTC
### Server Implementation

Paper

### Server Version

1.21

### Describe the bug

The -e flag in the //paste command is ignored, and schemes are pasted without entities

https://github.com/user-attachments/assets/a27e65f8-0f3a-4494-bde3-f6581adc8344

https://github.com/user-attachments/assets/039e6a03-60b4-4594-88aa-ba4b957c32f0

### To Reproduce

1)Create and save schematic with TextDisplays
2)Load that schematic
3) Use //paste -e command

### Expected behaviour

Schem pasted together with entities

### Screenshots / Videos

Visible above

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/783ae9ae8e9a402e9ffeec305d0d5da4

### Fawe Version

FastAsyncWorldEdit-Bukkit-2.11.2-SNAPSHOT-899

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by SirYwell** [comment] 2024-10-07 14:48
I cannot reproduce this on the latest build. Could you retry, and if the problem still occurs, provide a schematic with which it happens?

**Comment by TomTeDev** [comment] 2024-10-08 10:33
[schematics.zip](https://github.com/user-attachments/files/17291950/schematics.zip)
The issue still exist on "FastAsyncWorldEdit-Bukkit-2.11.3-SNAPSHOT-934"

**Comment by SirYwell** [comment] 2024-10-09 16:07
It seems like your schematic contains block display entities with text display entities as passengers. In this case, this is a duplicate of  #2427.

**Comment by MongoPotato** [comment] 2024-10-18 23:00
Hello,

I think i have a similar problem with the newest FAWE release (2.11.2) for minecraft 1.21. 

## Server Implementation

Paper

## Fawe Debugpaste
https://athion.net/ISPaster/paste/view/e6a36f55835c45198c943e7ad922ee6a

I cannot manage to copy data in signs. It could be a mistake on my part. It works in WorldEdit while in FAWE it does not. 

## FAWE clip

https://github.com/user-attachments/assets/a6c8325c-c48d-4fe3-930d-a29e78880d84


## World edit clip

https://github.com/user-attachments/assets/42285933-404f-4faf-94ef-81fb48c149d9


Sorry for the bad video quality, but i had downgrade massively to fit the clips to 10Mb files.

**Comment by dordsor21** [comment] 2024-10-26 13:39
Duplicate of #2427

**Closed by dordsor21** 2024-10-26 13:39 UTC
Labels: Awaiting Response
