### ISSUE TITLE
//fixlighting error 

### ISSUE THREAD

**Issue by nuttyNaoko** [IntellectualSites/FastAsyncWorldEdit#339] opened 2020-02-14 19:05 UTC
FastAsyncWorldEdit Configuration Files:
http://athion.net/ISPaster/paste/view/50a8ad9cecd7473f9195b76187ed0a9a

FastAsyncWorldEdit Version Number: 
FAWE - 71, feb 7 2020 Build 71, Bukkit-Official(1.15-71;0047f20)

Spigot/Paper Version Number:
git-Paper-105 (MC:1.15.2)

Description of the problem:
I wanted to fix the lighting as I have always done, but this time I got an error in chat ( please report this, see console) and got following error in console:

[18:54:02 ERROR]: An unexpected error while handling a WorldEdit command
java.io.IOException: Failed to upload files: you need to wait 4 minutes before creating a new paste
        at com.boydti.fawe.util.IncendoPaster.debugPaste(IncendoPaster.java:264) ~[?:?]
        at com.sk89q.worldedit.command.WorldEditCommands.report(WorldEditCommands.java:139) ~[?:?]
        at com.sk89q.worldedit.command.WorldEditCommandsRegistration.cmd$report(WorldEditCommandsRegistration.java:203) ~[?:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:158) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$15(PlatformCommandManager.java:685) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:701) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:687) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$13(PlatformCommandManager.java:657) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-105]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-105]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-105]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**How to replicate**:
just doing //fixlighting

**Plugins being used on the server:**
Already listed on the Incendo Paste Viewer

![Capture](https://user-images.githubusercontent.com/61063450/74559658-39e7b880-4f65-11ea-8ae3-aef30074e393.PNG)

**Comment by MattBDev** [comment] 2020-02-14 19:19
Duplicate of....a lot of issues.

**Closed by MattBDev** 2020-02-14 19:19 UTC
Labels: Requires Testing
