### ISSUE TITLE
FAWE doesn't work anymore

### ISSUE THREAD

**Issue by Fargus5** [IntellectualSites/FastAsyncWorldEdit#846] opened 2021-01-13 04:23 UTC
Minecraft PAPER 1.16.3
Fawe Lates update 1.16 #540

**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**: https://log.mtxserv.com/HUNukM0

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):     1.16 #540
- Spigot/Paper Version Number (`/version`):     Paper 1.16.3
- Minecraft Version: [e.g. 1.16.4]     1.16.3

**Describe the bug**

The plugin doesn't work...
I have this error for example:
```

[05:20:09] [Server thread/INFO]: Fargus issued server command: //wand
--
2083 | [05:20:09] [ForkJoinPool-8-worker-3/ERROR]: An unexpected error while handling a WorldEdit command
2084 | java.lang.NullPointerException: null
2085 | at net.minecraft.server.v1_16_R2.EntityPlayer.a(EntityPlayer.java:1361) ~[patched_1.16.3.jar:git-Paper-253]
2086 | at net.minecraft.server.v1_16_R2.EntityPlayer.updateInventory(EntityPlayer.java:1356) ~[patched_1.16.3.jar:git-Paper-253]
2087 | at org.bukkit.craftbukkit.v1_16_R2.entity.CraftPlayer.updateInventory(CraftPlayer.java:884) ~[patched_1.16.3.jar:git-Paper-253]
2088 | at com.sk89q.worldedit.bukkit.BukkitPlayer.giveItem(BukkitPlayer.java:173) ~[?:?]
2089 | at com.sk89q.worldedit.extension.platform.PlayerProxy.giveItem(PlayerProxy.java:103) ~[?:?]
2090 | at com.sk89q.worldedit.command.SelectionCommands.wand(SelectionCommands.java:299) ~[?:?]
2091 | at com.sk89q.worldedit.command.SelectionCommandsRegistration.cmd$_wand(SelectionCommandsRegistration.java:407) ~[?:?]
2092 | at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[?:?]
2093 | at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:693) ~[?:?]
2094 | at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:709) ~[?:?]
2095 | at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:695) ~[?:?]
2096 | at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$null$13(PlatformCommandManager.java:665) ~[?:?]
2097 | at com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:697) ~[?:?]
2098 | at com.boydti.fawe.object.task.AsyncNotifyQueue.lambda$run$0(AsyncNotifyQueue.java:27) ~[?:?]
2099 | at com.boydti.fawe.object.task.AsyncNotifyQueue.lambda$call$1(AsyncNotifyQueue.java:44) ~[?:?]
2100 | at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448) ~[?:?]
2101 | at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
2102 | at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
2103 | at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
2104 | at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
2105 | at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[?:?]


```

**To Reproduce**
1. Run  to '...'

**Plugins being used on the server**

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [] I made sure the bug/error is not caused by any other plugin

**Comment by Fargus5** [comment] 2021-01-13 04:24
I was not updating fawe because I'm using mc 1.16.3... but cause the plugin stopped to work I think that updating fawe was a good idea...

I had the same error while executing the command //wand ...

I don't know why fawe stopped to work...

**Comment by Fargus5** [comment] 2021-01-13 04:25
Plugin List:


Paper on Bukkit 1.16.3-R0.1-SNAPSHOT: PlugMan 2.1.7; PermissionEffect 1.0.0-SNAPSHOT; Oh_the_dungeons_youll_go 13.0; ChestSort 9.0.0; Recount 3.4.1; EpicPluginLib 1.6.7; STN-Studios-API 4.2.0-Gateway Intents; CMILib 1.0.0.2; AlmostFlatLandsReloaded 1.2.7; LoneLibs 1.0.6; InventoryRollback 1.4.0; PermissionsEx 1.23.4; ItemBridge 1.0.5; PluginConstructorAPI 1.0.52; PlaceholderAPI 2.10.9; InsaneAnnouncer 1.0.4; SkinsRestorer 13.8.6; LightAPI 3.4.6; PacketListenerApi 3.7.8-SNAPSHOT; BuycraftX 12.0.6; Votifier 2.7.1; MotionCaptureRewritten 2.0.3; BeehivesPro 1.1.2; CS-CoreLib DEV - 92 (git e9150d72); Vault 1.7.3-b131; MinecraftItaliaRewards 1.0.0-ALPHA; ViaVersion 3.2.1; DiscordNotif 2.5-fix; MyCommand 5.6.8; GUIPlus 2.8; GlowAPI 1.4.14-SNAPSHOT; Multiverse-Core 4.2.2-b812; ProtocolLib 4.6.0-SNAPSHOT-b482; Citizens 2.0.27-SNAPSHOT (build 2158); Sentinel 2.2.0-SNAPSHOT (build 375); FastAsyncWorldEdit 1.16-540,b4d7562; Reporter 3.3.4; WorldEditSelectionVisualizer 2.0.7; VoidTeleport 2.3.5; GPS 2.19.5; SuperTrailsPro v1.2.13; WorldGuard 7.0.4+f7ff984; DeathTotems 1.2.1; Multiverse-Inventories 4.2.1-b490; BigDoors Alpha 0.1.8.28 (b882); PlayMoreSounds 3.4.0; CitizensGUI 1.5; BPS-Premium 12.7.9; InsaneShops 1.3.0; HeadDatabase 4.13.2; LibsDisguises 10.0.21; AdvancedAchievements 6.3.0; HideAndSeek 4.1; CitizensText 1.19.3; BKCommonLib 1.16.4-v2; AuthMe 5.6.0-SNAPSHOT-b2436; HolographicDisplays 2.4.4; Spartan Build 386; Images 2.1.4; DangerousCaves 2.2.12-SNAPSHOT,22; The_Gate 0.1.10-2mc1.16.3; QualityArmory 1.1.176; Skript 2.5.1; Paintball 2.9.0; FastLogin 1.11-SNAPSHOT-9ff404a; BotSentry 8.7.1-ARES; QualityArmoryVehicles 1.0.81; PictureLogin 1.6; SkQuery 4.1.4; LiteBans 2.6; AlonsoLeaderboards 1.3-BETA; ServerBooster 1.0.50; Skywars 5.4.1; Skywars-Extension 1.6.1; CMI 8.8.0.2; MythicMobs 4.11.0-BETA-79e173ec; CMIEInjector 1.0.2.3; BeautyQuests 0.18.5; VotingPlugin 6.0.4; FogusCore 1.9.9; ItemsAdder 2.1.24; WorldGuardExtraFlags 4.1.5-SNAPSHOT; MythicMobsExtension 1.736a-SNAPSHOT; BigDoorsOpener 2.3.1; RPGMoney 1.1.25; RPGBank 1.0.12; ModelEngine R1.0.9; MythicMobsMobsGUI 1; EpicBackpacks 1.2.7; PremiumVanish 2.6.2; InteractionVisualizer 1.13.10; ItemEdit 2.4; DiscordSRV 1.21.2; DiscordSRVUtils 1.1.11; PrivateMessages 3.0-Beta6; UltimateTimber 2.2; Kingdoms 1.10.13.4.1; MyPet 3.11; MyPetGUI 1.05; SkillsPro 18.10.0.1.1; skRayFall 1.9.21; Slimefun DEV - 780 (git bc8d72b9); ExtraTools DEV - 23 (git 9299a65c); PrivateStorage DEV - 15 (git a0fbc572); GlobalWarming DEV - 7 (git 25114c13); ChestTerminal DEV - 38 (git c024be5c); FoxyMachines DEV - 10 (git 666e405d); MoreTools DEV - 9 (git e8cfb32c); FluffyMachines DEV - 59 (git fa52f3b1); SoundMuffler DEV - 19 (git 5caef292); EcoPower DEV - 3 (git 18ba903d); ExtraGear DEV - 12 (git 4570ea2c); ExoticGarden DEV - 65 (git 02b9f1f1); Liquid DEV - 6 (git 319b40ca); DynaTech DEV - 22 (git 1b6aee96); MeteoritesPro 1.5.3; CoreProtect 19.4; CoreProtectTNT 1.0; LightCleaner 1.16.4-v1; CMIPaperLib 1.0.0 | Paper on Bukkit 1.16.3-R0.1-SNAPSHOT: PlugMan 2.1.7; PermissionEffect 1.0.0-SNAPSHOT; Oh_the_dungeons_youll_go 13.0; ChestSort 9.0.0; Recount 3.4.1; EpicPluginLib 1.6.7; STN-Studios-API 4.2.0-Gateway Intents; CMILib 1.0.0.2; AlmostFlatLandsReloaded 1.2.7; LoneLibs 1.0.6; InventoryRollback 1.4.0; PermissionsEx 1.23.4; ItemBridge 1.0.5; PluginConstructorAPI 1.0.52; PlaceholderAPI 2.10.9; InsaneAnnouncer 1.0.4; SkinsRestorer 13.8.6; LightAPI 3.4.6; PacketListenerApi 3.7.8-SNAPSHOT; BuycraftX 12.0.6; Votifier 2.7.1; MotionCaptureRewritten 2.0.3; BeehivesPro 1.1.2; CS-CoreLib DEV - 92 (git e9150d72); Vault 1.7.3-b131; MinecraftItaliaRewards 1.0.0-ALPHA; ViaVersion 3.2.1; DiscordNotif 2.5-fix; MyCommand 5.6.8; GUIPlus 2.8; GlowAPI 1.4.14-SNAPSHOT; Multiverse-Core 4.2.2-b812; ProtocolLib 4.6.0-SNAPSHOT-b482; Citizens 2.0.27-SNAPSHOT (build 2158); Sentinel 2.2.0-SNAPSHOT (build 375); FastAsyncWorldEdit 1.16-540,b4d7562; Reporter 3.3.4; WorldEditSelectionVisualizer 2.0.7; VoidTeleport 2.3.5; GPS 2.19.5; SuperTrailsPro v1.2.13; WorldGuard 7.0.4+f7ff984; DeathTotems 1.2.1; Multiverse-Inventories 4.2.1-b490; BigDoors Alpha 0.1.8.28 (b882); PlayMoreSounds 3.4.0; CitizensGUI 1.5; BPS-Premium 12.7.9; InsaneShops 1.3.0; HeadDatabase 4.13.2; LibsDisguises 10.0.21; AdvancedAchievements 6.3.0; HideAndSeek 4.1; CitizensText 1.19.3; BKCommonLib 1.16.4-v2; AuthMe 5.6.0-SNAPSHOT-b2436; HolographicDisplays 2.4.4; Spartan Build 386; Images 2.1.4; DangerousCaves 2.2.12-SNAPSHOT,22; The_Gate 0.1.10-2mc1.16.3; QualityArmory 1.1.176; Skript 2.5.1; Paintball 2.9.0; FastLogin 1.11-SNAPSHOT-9ff404a; BotSentry 8.7.1-ARES; QualityArmoryVehicles 1.0.81; PictureLogin 1.6; SkQuery 4.1.4; LiteBans 2.6; AlonsoLeaderboards 1.3-BETA; ServerBooster 1.0.50; Skywars 5.4.1; Skywars-Extension 1.6.1; CMI 8.8.0.2; MythicMobs 4.11.0-BETA-79e173ec; CMIEInjector 1.0.2.3; BeautyQuests 0.18.5; VotingPlugin 6.0.4; FogusCore 1.9.9; ItemsAdder 2.1.24; WorldGuardExtraFlags 4.1.5-SNAPSHOT; MythicMobsExtension 1.736a-SNAPSHOT; BigDoorsOpener 2.3.1; RPGMoney 1.1.25; RPGBank 1.0.12; ModelEngine R1.0.9; MythicMobsMobsGUI 1; EpicBackpacks 1.2.7; PremiumVanish 2.6.2; InteractionVisualizer 1.13.10; ItemEdit 2.4; DiscordSRV 1.21.2; DiscordSRVUtils 1.1.11; PrivateMessages 3.0-Beta6; UltimateTimber 2.2; Kingdoms 1.10.13.4.1; MyPet 3.11; MyPetGUI 1.05; SkillsPro 18.10.0.1.1; skRayFall 1.9.21; Slimefun DEV - 780 (git bc8d72b9); ExtraTools DEV - 23 (git 9299a65c); PrivateStorage DEV - 15 (git a0fbc572); GlobalWarming DEV - 7 (git 25114c13); ChestTerminal DEV - 38 (git c024be5c); FoxyMachines DEV - 10 (git 666e405d); MoreTools DEV - 9 (git e8cfb32c); FluffyMachines DEV - 59 (git fa52f3b1); SoundMuffler DEV - 19 (git 5caef292); EcoPower DEV - 3 (git 18ba903d); ExtraGear DEV - 12 (git 4570ea2c); ExoticGarden DEV - 65 (git 02b9f1f1); Liquid DEV - 6 (git 319b40ca); DynaTech DEV - 22 (git 1b6aee96); MeteoritesPro 1.5.3; CoreProtect 19.4; CoreProtectTNT 1.0; LightCleaner 1.16.4-v1; CMIPaperLib 1.0.0
-- | --
Paper on Bukkit 1.16.3-R0.1-SNAPSHOT: PlugMan 2.1.7; PermissionEffect 1.0.0-SNAPSHOT; Oh_the_dungeons_youll_go 13.0; ChestSort 9.0.0; Recount 3.4.1; EpicPluginLib 1.6.7; STN-Studios-API 4.2.0-Gateway Intents; CMILib 1.0.0.2; AlmostFlatLandsReloaded 1.2.7; LoneLibs 1.0.6; InventoryRollback 1.4.0; PermissionsEx 1.23.4; ItemBridge 1.0.5; PluginConstructorAPI 1.0.52; PlaceholderAPI 2.10.9; InsaneAnnouncer 1.0.4; SkinsRestorer 13.8.6; LightAPI 3.4.6; PacketListenerApi 3.7.8-SNAPSHOT; BuycraftX 12.0.6; Votifier 2.7.1; MotionCaptureRewritten 2.0.3; BeehivesPro 1.1.2; CS-CoreLib DEV - 92 (git e9150d72); Vault 1.7.3-b131; MinecraftItaliaRewards 1.0.0-ALPHA; ViaVersion 3.2.1; DiscordNotif 2.5-fix; MyCommand 5.6.8; GUIPlus 2.8; GlowAPI 1.4.14-SNAPSHOT; Multiverse-Core 4.2.2-b812; ProtocolLib 4.6.0-SNAPSHOT-b482; Citizens 2.0.27-SNAPSHOT (build 2158); Sentinel 2.2.0-SNAPSHOT (build 375); FastAsyncWorldEdit 1.16-540,b4d7562; Reporter 3.3.4; WorldEditSelectionVisualizer 2.0.7; VoidTeleport 2.3.5; GPS 2.19.5; SuperTrailsPro v1.2.13; WorldGuard 7.0.4+f7ff984; DeathTotems 1.2.1; Multiverse-Inventories 4.2.1-b490; BigDoors Alpha 0.1.8.28 (b882); PlayMoreSounds 3.4.0; CitizensGUI 1.5; BPS-Premium 12.7.9; InsaneShops 1.3.0; HeadDatabase 4.13.2; LibsDisguises 10.0.21; AdvancedAchievements 6.3.0; HideAndSeek 4.1; CitizensText 1.19.3; BKCommonLib 1.16.4-v2; AuthMe 5.6.0-SNAPSHOT-b2436; HolographicDisplays 2.4.4; Spartan Build 386; Images 2.1.4; DangerousCaves 2.2.12-SNAPSHOT,22; The_Gate 0.1.10-2mc1.16.3; QualityArmory 1.1.176; Skript 2.5.1; Paintball 2.9.0; FastLogin 1.11-SNAPSHOT-9ff404a; BotSentry 8.7.1-ARES; QualityArmoryVehicles 1.0.81; PictureLogin 1.6; SkQuery 4.1.4; LiteBans 2.6; AlonsoLeaderboards 1.3-BETA; ServerBooster 1.0.50; Skywars 5.4.1; Skywars-Extension 1.6.1; CMI 8.8.0.2; MythicMobs 4.11.0-BETA-79e173ec; CMIEInjector 1.0.2.3; BeautyQuests 0.18.5; VotingPlugin 6.0.4; FogusCore 1.9.9; ItemsAdder 2.1.24; WorldGuardExtraFlags 4.1.5-SNAPSHOT; MythicMobsExtension 1.736a-SNAPSHOT; BigDoorsOpener 2.3.1; RPGMoney 1.1.25; RPGBank 1.0.12; ModelEngine R1.0.9; MythicMobsMobsGUI 1; EpicBackpacks 1.2.7; PremiumVanish 2.6.2; InteractionVisualizer 1.13.10; ItemEdit 2.4; DiscordSRV 1.21.2; DiscordSRVUtils 1.1.11; PrivateMessages 3.0-Beta6; UltimateTimber 2.2; Kingdoms 1.10.13.4.1; MyPet 3.11; MyPetGUI 1.05; SkillsPro 18.10.0.1.1; skRayFall 1.9.21; Slimefun DEV - 780 (git bc8d72b9); ExtraTools DEV - 23 (git 9299a65c); PrivateStorage DEV - 15 (git a0fbc572); GlobalWarming DEV - 7 (git 25114c13); ChestTerminal DEV - 38 (git c024be5c); FoxyMachines DEV - 10 (git 666e405d); MoreTools DEV - 9 (git e8cfb32c); FluffyMachines DEV - 59 (git fa52f3b1); SoundMuffler DEV - 19 (git 5caef292); EcoPower DEV - 3 (git 18ba903d); ExtraGear DEV - 12 (git 4570ea2c); ExoticGarden DEV - 65 (git 02b9f1f1); Liquid DEV - 6 (git 319b40ca); DynaTech DEV - 22 (git 1b6aee96); MeteoritesPro 1.5.3; CoreProtect 19.4; CoreProtectTNT 1.0; LightCleaner 1.16.4-v1; CMIPaperLib 1.0.0

**Comment by lusu007** [comment] 2021-01-13 08:17
I'll summarize this somewhat confusing bug report, as we are experiencing exactly the same or a similar problem.

All actions performed with FAWE work without problems, but they are not displayed. The changes are only visible when the chunks are unloaded and loaded again. Also F3+A is is not sufficient.

Build 549 works without any problems. I think something in #838 broke something.


Server information:
Debug Paste: https://athion.net/ISPaster/paste/view/e64973a2c55249cd9e02d6e8c38ee45d
FAWE Version: Bukkit-Official(1.16-540;b4d7562)
Paper Version: git-Paper-403 (MC: 1.16.4)
Plugins: Arceon, Builders-Utilities, BungeeTabListPlus, Essentials, FastAsyncWorldEdit (WorldEdit), goBrush, goPaint, HeadDatabase, Hyperverse, LegendEssentials, LegendSchematicScatter, LuckPerms, Vault, VoidGenerator, VoxelSniper, WorldGuard

**Comment by LaurenceBarnes** [comment] 2021-01-13 08:43
I think I experience the same issue I think, but I executed the command twice or more often until it was visible. Was gonna report this until I saw this post.

**Comment by lusu007** [comment] 2021-01-13 08:55
@LaurenceBarnes just downgrade to version 549 until this is fixed. 😄

**Comment by LaurenceBarnes** [comment] 2021-01-13 09:01
you mean 539? xD

**Comment by lusu007** [comment] 2021-01-13 09:08
Oh shit, my bad. Yes I mean 539.

Or just update to 549 this bug should be fixed there as well xD

**Comment by aurorasmiles** [comment] 2021-01-13 11:05
Update FAWE

**Comment by lusu007** [comment] 2021-01-13 11:08
To which build @aurorasmiles ? 
We are talking about the latest one.

**Comment by aurorasmiles** [comment] 2021-01-13 11:11
You confused me with your earlier comment about 549 lol

**Comment by lusu007** [comment] 2021-01-13 11:12
Not only you. I think @LaurenceBarnes too... My bad sorry 😃

**Comment by aurorasmiles** [comment] 2021-01-13 11:17
I can't replicate that issue.
@lusu007 please open a seperate issue for yours, as it doesn't seem to be related at all. (tho, I can't replicate that either)

**Closed by aurorasmiles** 2021-01-13 11:17 UTC
Labels: Requires Testing

**Comment by Fargus5** [comment] 2021-01-13 12:40
Ticket has been closed with some solution?
What we have to do? waiting that this will be fixed? @aurorasmiles  thanks

**Comment by aurorasmiles** [comment] 2021-01-13 13:43
I can't replicate the issue and you didn't provide all the information in the template.

**Comment by Fargus5** [comment] 2021-01-13 13:46
This is not a professional reason to close the ticket.
As you read I'm not the only one that have this problem.... more than give you the error what do you want that I do?
I cannot do debugpaste because the command doesn't work.

I do //fawe and there is nothing in chat

I do //wand and I have the error that I gave to u...

if the problem persist you don't close it....

**Comment by aurorasmiles** [comment] 2021-01-13 13:52
The issue described by lusu is something completely different.
Your issue is most likely caused by one of your countless (outdated) plugins. Try to test without plugins and see if that issue still persists. If it does, please open a new issue providing all the required information.
