### ISSUE TITLE
//regen Spitting Errors in Console when attempting to execute command

### ISSUE THREAD

**Issue by MetalMinurz** [IntellectualSites/FastAsyncWorldEdit#1288] opened 2021-09-10 16:48 UTC
### Server Implementation

Spigot

### Server Version

1.17.1

### Describe the bug

When attempting to use //regen after selecting an area, the region regenerates incorrectly compared to vanilla generation and a series of errors appears in console.

Some of the effects of the error are seen ingame, such as grass not generating on the surface or bedrock not generating. Cave generation will also be slightly different.

Here is a paste of the error in console: [](https://pastebin.com/gyysY9Ft)

### To Reproduce

1. Select an area larger than 2000 blocks. Try to include the surface grass or bedrock for the clearest effect.
2. Run //regen ingame.
3. Errors should appear in console and the regenerated region will look different than the original vanilla terrain.

### Expected behaviour

After using //regen I was expecting the area to generate as if it were being generated by minecraft for the first time, with identical structure and landform.

### Screenshots / Videos

![2021-09-10_11 42 44](https://user-images.githubusercontent.com/30448157/132888443-89e439c6-cb1c-4657-9280-713f0f7d0748.png)
![2021-09-10_11 43 03](https://user-images.githubusercontent.com/30448157/132888446-64e73723-5d5f-4974-8a86-db0f522514aa.png)

### Error log (if applicable)

https://pastebin.com/gyysY9Ft

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/b12a1d36b6b544ffb7890ad1fa2b091e

### Fawe Version

FastAsyncWorldEdit version 1.17-217;c16212e

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

### Anything else?

I've tested //regen in multiple areas of the overworld, and the issue remains consistent. I also am running an anticheat on the server (Vulcan), but I highly doubt this is the cause of the issue.

**Comment by dordsor21** [comment] 2021-09-10 16:48
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit-Adapters/issues/16

**Closed by dordsor21** 2021-09-10 16:48 UTC
Labels: Requires Testing
