### ISSUE TITLE
Plot clear and plot setbiome spam errors

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit#861] opened 2021-01-17 17:08 UTC
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**Fawe config files**: https://haste.athion.net/qeyibecixi.coffeescript

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`): FastAsyncWorldEdit version 1.16-560;6895fe3
- PlotSquared version number: PlotSquared-Bukkit-5.13.10-Premium
- Spigot/Paper Version Number (`/version`): git-Paper-428 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
- Minecraft Version: 1.16.5     

**Describe the bug**
Doing a /plot clear works in game but spams errors in the console: https://haste.athion.net/oqofapojel.md but /plot setbiome [biome] also has the same problem

**To Reproduce**
1. Download paper 1.16.5
2. Use /plot clear

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment] 2021-01-17 17:31
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/859

**Closed by N0tMyFaultOG** 2021-01-17 17:31 UTC
Labels: Requires Testing
