### ISSUE TITLE
FAWE resetting other chunk alterations on operations

### ISSUE THREAD

**Issue by dbhatfield** [IntellectualSites/FastAsyncWorldEdit#329] opened 2020-01-31 02:03 UTC
# Bug report for FastAsyncWorldEdit 1.14.4

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

https://athion.net/ISPaster/paste/view/e64bc2ae12a348838b79373480a4e19d

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

(FAWE) ------------------ Platforms ------------------
* Bukkit-Official(1.15-58;336e411)
(FAWE) ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official

**[REQUIRED] Spigot/Paper Version Number:** 

Server version: Paper(43) 1.15.1-R0.1-SNAPSHOT

**[REQUIRED] Description of the problem:**

The bug is a chunk based one in where when a player enters a chunk without exiting and makes a FAWE operation, any altered blocks by any means other than FAWE within that chunk since they entered will be reset to their state prior to the player entering say for the operation itself. If a player leaves the chunk of the operation and re-enters, the blocks will be updated to work correctly again besides further updates repeating the issue.

From what I can see the issue is consistent over my own development server along with my network's and another server I was testing FAWE on. Many of my staff have also reported the same issue as well making building with FAWE difficult. The issue also does not generate any console logs or exceptions.

Video documenting issue:
[https://vimeo.com/388392309](url)

**How to replicate**:

- Open Minecraft's chunk viewer with F3 + G
- Enter a chunk and make any blocks alterations within it in any way but FAWE without leaving
- Making any FAWE operation inside of the chunk will cause the altered blocks to reset to their prior state

**Plugins being used on the server:**

CMI (Like essentials)
FAWE Build 58
Vault
ProtocolLib
WorldGuard 7.0.2
Generated DummyFawe jar

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)
1.15.1
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by IronApollo** [comment] 2020-01-31 17:19
Confirmed bug. Priority placed on this since it's very volatile, potentially destructive and counteractive to the intended use of the plugin.

**Comment by IronApollo** [comment] 2020-02-02 01:31
Closing this issue and marking as resolved (https://github.com/IntellectualSites/FastAsyncWorldEdit/commit/4f3db6f3dae7add494349fd930f914119b164825) unless someone either says the issue is not resolved or the commit has to be reverted.

**Closed by IronApollo** 2020-02-02 01:31 UTC
Labels: Approved, Priority, Under investigation, [!] Bug
