### ISSUE TITLE
Enable making edits to PlotSquared plots while standing outside it

### ISSUE THREAD

**Issue by Schuwi** [IntellectualSites/FastAsyncWorldEdit#2052] opened 2022-12-22 12:10 UTC
### What feature do you want to see added?

Currently when worldedit edits are restricted by plots for a player, the player must be inside the plot where they are making edits at the time the edit is executed (i.e. when the command is entered or the brush is used). This can be annoying especially if the plots are small and brushes are used (i.e. flying around outside the plot to get a better perspective).

Ideally the check would ignore the location of the player and only depend on what area the selection/brush is targeting.

Alternatively checking the plot nearest to the player (if they are not on a plot, e.g. on a road between plots) would already be helpful. Even better if the check only considers plots where the player is allowed to build.

### Are there any alternatives?

As it stands, I don't know of any alternative solution except standing on the plot while doing edits.

### Anything else?

#1946 might be related

**Comment by NotMyFault** [comment] 2022-12-23 11:24
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1946

**Closed by NotMyFault** 2022-12-23 11:24 UTC
Labels: Enhancement
