### ISSUE TITLE
Not Pasting Tile Entities (Item Frames)

### ISSUE THREAD

**Issue by lewysDavies** [IntellectualSites/FastAsyncWorldEdit#517] opened 2020-06-25 16:07 UTC
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
Literally Default, Nothing changed.

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
FastAsyncWorldEdit-1.15-256

**[REQUIRED] Spigot/Paper Version Number:** 
Paper MC version 1.15.2. (git-Paper-339)

**[REQUIRED] Description of the problem:**
When pasting a schematic with ItemFrames, they are not included. When pasting with standard WorldEdit, they paste fine.
I am assuming this issue might affect Tile entities as a whole

**How to replicate**:
[test schematic.zip](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/4832487/test.schematic.zip)
Use up-to-date WE with //paste -e (Works fine, pastes entities).
Use FAWE (does not paste entities). With or without -e

**Plugins being used on the server:**
Blacked out plugins are completely custom and have 0 impact on WE/FAWE
![image](https://user-images.githubusercontent.com/6516130/85755887-3ed42a00-b706-11ea-8a9e-a85767b0f683.png)

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by SirYwell** [comment] 2020-06-25 16:18
Related to #303 #308 #442 #488 #502.

**Comment by aurorasmiles** [comment] 2020-06-25 16:20
Actually,
Duplicate of #303

**Closed by aurorasmiles** 2020-06-25 16:20 UTC
Labels: Requires Testing
