### ISSUE TITLE
Fixlighting sometimes results in an error

### ISSUE THREAD

**Issue by TheoRetisch1** [IntellectualSites/FastAsyncWorldEdit#782] opened 2020-12-13 17:06 UTC
**/fawe debugpaste**:
https://athion.net/ISPaster/paste/view/c74e95dd5bbc4137a203132a016d4d57

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`): 1.16-462;04ba545
- Spigot/Paper Version Number (`/version`): Paper build 324
- Minecraft Version: 1.16.4

**Describe the bug**
When I repair light using `//removelighting` and `//fixlighting`, an error occurs in some chunks when using `//fixlighting`. There, the light cannot be set again with the help of `//fixlighting`. In other places, it works perfectly.
**Error**: https://pastebin.com/7eZfDNde

**To Reproduce**
1. `//pos1` + `//pos2`
2. `//outset 10`
3. `//removelighting`
4. `//fixlighting`
However, the error does not always occur.

**Plugins being used on the server**
ChatControl, CMI, CMIEInjector, CMIPaperLib, FastAsyncWorldEdit, LuckPerms, Multiverse-Core, Nucleus, rAPI, rAPInms, StaffStuff, Vault, WirsingFix, WorldGuard, WorldGuardEvents, WorldGuardExtraFlags

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment] 2020-12-15 23:45
https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/682

**Comment by aurorasmiles** [comment] 2020-12-16 12:35
Duplicate of #682

**Closed by aurorasmiles** 2020-12-16 12:35 UTC
Labels: Requires Testing
