### ISSUE TITLE
Error in stacking

### ISSUE THREAD

**Issue by craftyfoxe** [IntellectualSites/FastAsyncWorldEdit#1559] opened 2022-01-23 04:28 UTC
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

I just selected an area and tried to stack, but it had an error

### To Reproduce

select two positions try //stack

### Expected behaviour

to stack it

### Screenshots / Videos

![2022-01-22_23 22 43](https://user-images.githubusercontent.com/48233056/150664813-522c7416-2a6e-4a67-b0fd-234688dd58c5.png)
https://cdn.discordapp.com/attachments/334547947293245442/934665472354422814/2022-01-22_23.22.43.png

### Error log (if applicable)

https://paste.gg/p/anonymous/f045e346795c4b9c8801c88b6f353b7b

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/5a55b427245d4086ba4ae9e02786c33e

### Fawe Version

Version 2.0.1-SNAPSHOT-73;016b4ba

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

I upgraded from Build#68 and that build everything was working just fine before

**Comment by NotMyFault** [comment] 2022-01-24 11:44
Based on the information provided, I am not replicate that.

**Comment by PierreSchwang** [comment] 2022-02-25 22:45
Duplicate of #1436

**Comment by dordsor21** [comment] 2022-03-10 14:22
Technically not a duplicate

**Comment by dordsor21** [comment] 2022-06-14 15:56
This will have been caused by the use of CoreProtect, however, as CoreProtect now inserts its Extent at a different stage, the bug was effectively fixed for this specific case. Otherwise, this will be fixed by #1809

**Closed** 2022-06-16 14:23 UTC
Labels: Bug, Approved
