### ISSUE TITLE
FastAsyncWorldEdit-1.16-302 /up 1 working but Give an error in console and in game

### ISSUE THREAD

**Issue by dark-tet** [IntellectualSites/FastAsyncWorldEdit#538] opened 2020-07-18 09:15 UTC
## in game error
<img src="https://i.imgur.com/jHVAjdI.png" alt="Game Error" width="450">
game image
<img src="https://i.imgur.com/BXymi0D.png" alt="Stuck in a block" width="250">

**Comment by N0tMyFaultOG** [comment] 2020-07-20 10:28
Duplicate of #542

**Closed by N0tMyFaultOG** 2020-07-20 10:28 UTC
Labels: Requires Testing
