### ISSUE TITLE
Said to report it in console :D

### ISSUE THREAD

**Issue by DoogiePC** [IntellectualSites/FastAsyncWorldEdit#986] opened 2021-03-20 21:52 UTC
### Server Implementation

Tuinity

### Server Version

1.16.5

### Describe the bug

Worldedit works for a few hours or more, its random really, then suddenly Worldedit wont work, any command you try except //cancel just doesnt do anything, no message is sent or anything. It's as if you never ran the command.

https://pastebin.com/kW1cnXf1

### To Reproduce

Not sure how, but the erorr might help?

### Expected behaviour

I expected the worldedit command to run but nothing happened.

### Fawe Debugpaste

Cant run commands :(

### Fawe Version

FastAsyncWorldEdit-1.16-626

**Comment by NotMyFault** [comment] 2021-03-20 22:22
Duplicate of something else I don't have the ID of rn.

**Closed by NotMyFault** 2021-03-20 22:22 UTC
Labels: Requires Testing
