### ISSUE TITLE
Errors in console on regen. Result was fine though

### ISSUE THREAD

**Issue by EvilOlaf** [IntellectualSites/FastAsyncWorldEdit#1615] opened 2022-02-16 14:09 UTC
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

Marked a bit area that has been severely damaged and run `regen`. Took about 80 seconds to complete and the result seemed just fine. However I saw a few errors popped up in console. Not sure if a big deal or not. Probably not.

### To Reproduce

**Could not reproduce (yet).**

- Play with hugh spheres of stone and tnt and let it destroy the environment (yes, it takes quite a while for thousands of TNT to detonate).
- Mark area of about 500x500 with expand vert
- Run `//regen`
- wait

### Expected behaviour

Regenerate without throwing errors I guess.

### Screenshots / Videos

Did not took any since I noticed as things were already done, sorry.

### Error log (if applicable)

https://paste.gg/p/anonymous/3d7748ba25c84aa3b4e03f7fe8b84f67

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/59d492c9c7f647ebbf9efa4f018b4362

### Fawe Version

2.0.2-SNAPSHOT-94;cf0a21d

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

I hope I did not miss any relevant information. If so please let me know and I come back to it asap.

Cheers

**Comment by NotMyFault** [comment] 2022-03-08 18:14
Can you try to replicate that on an up to date version of Fawe on Paper 1.18.2?

**Comment by EvilOlaf** [comment] 2022-03-08 19:15
Yeah I tried that already with close to 62 mio blocks at peak but no luck. Must have been a one time fluke ¯\_(ツ)_/¯

**Comment by PierreSchwang** [comment] 2022-03-08 19:15
Gonna create a PR in a few, where the issue is fixed in < 1.18.2

**Comment by EvilOlaf** [comment] 2022-03-08 19:17
Have to correct myself. Last expansion was 62 mio blocks. Summed up 246 mio.

**Closed** 2022-03-28 17:33 UTC
Labels: Bug, Approved
