### ISSUE TITLE
Biome bug

### ISSUE THREAD

**Issue by TheSirCororo** [IntellectualSites/FastAsyncWorldEdit#1234] opened 2021-08-18 15:24 UTC
### Server Implementation

Tuinity

### Server Version

1.16.5

### Describe the bug

Player attempt to unlink or delete PlotSquared plots and get FAWE error, plots didn't deleted
We attempt to install latest version and bug didn't fixed
Exception:
![image](https://user-images.githubusercontent.com/61053191/129925167-33c27051-608c-412f-8861-b17969d327f9.png)

### To Reproduce

1. Go to linked plots from PlotSquared
2. Type /p delete | /p unlink
3. Get error to console

### Expected behaviour

Plots unlinked or deleted without error

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/61053191/129925167-33c27051-608c-412f-8861-b17969d327f9.png)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/21483528a33a49bc995ba11efb6b438d (this is current paste, with old version, before this we use FAWE-157)

### Fawe Version

FastAsyncWorldEdit 1.17-157

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by NotMyFault** [comment] 2021-08-18 15:25
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1233

**Comment by 1Pootis1** [comment] 2021-08-18 15:26
Nice XD

**Closed by NotMyFault** 2021-08-18 15:25 UTC
Labels: Invalid, Duplicate
