### ISSUE TITLE
Sphere Brush size 1 and below isn't working. Build 260 - 1.15.2

### ISSUE THREAD

**Issue by DecoratedMC** [IntellectualSites/FastAsyncWorldEdit#507] opened 2020-06-14 23:40 UTC
The smallest possible size for a sphere brush is 1.3. No errors of any kind to be found.
(Template wasn't visible to me before making this, disregard this post)

**Comment by aurorasmiles** [comment] 2020-06-15 09:45
Duplicate of #241

**Closed** 2020-06-15 09:45 UTC
