### ISSUE TITLE
Error on //copy in lastest version

### ISSUE THREAD

**Issue by GreenChennai** [IntellectualSites/FastAsyncWorldEdit#371] opened 2020-03-20 04:09 UTC
An error occurred when using the instruction //copy
Unable to copy and appear error code

MC Core Spigot
MC Ver 1.14.4

Error Code
```
[10:45:36 ERROR]: An unexpected error while handling a WorldEdit command
java.lang.RuntimeException: java.io.IOException: The requested operation cannot be performed on a file opened with the user mapping area。
        at com.boydti.fawe.object.clipboard.DiskOptimizedClipboard.<init>(DiskOp
timizedClipboard.java:108) ~[?:?]
        at com.boydti.fawe.object.clipboard.DiskOptimizedClipboard.<init>(DiskOp
timizedClipboard.java:66) ~[?:?]
        at com.sk89q.worldedit.extent.clipboard.Clipboard.create(Clipboard.java:
80) ~[?:?]
        at com.sk89q.worldedit.extent.clipboard.BlockArrayClipboard.<init>(Block
ArrayClipboard.java:79) ~[?:?]
        at com.sk89q.worldedit.command.ClipboardCommands.copy(ClipboardCommands.
java:135) ~[?:?]
        at com.sk89q.worldedit.command.ClipboardCommandsRegistration.cmd$_copy(C
lipboardCommandsRegistration.java:280) ~[?:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:158)
~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$
handleCommandOnCurrentThread$15(PlatformCommandManager.java:685) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleC
ommandTask(PlatformCommandManager.java:701) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleC
ommandOnCurrentThread(PlatformCommandManager.java:687) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$
handleCommand$13(PlatformCommandManager.java:657) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.jav
a:84) ~[patched_1.14.4.jar:git-Paper-243]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsy
ncTask.java:54) ~[patched_1.14.4.jar:git-Paper-243]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSch
edulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-243]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:
1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?
:1.8.0_101]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.io.IOException: The requested operation cannot be performed on a file opened with the user mapping area
。
        at java.io.RandomAccessFile.setLength(Native Method) ~[?:1.8.0_101]
        at com.boydti.fawe.object.clipboard.DiskOptimizedClipboard.<init>(DiskOp
timizedClipboard.java:100) ~[?:?]
        ... 16 more
```

**Comment by aurorasmiles** [comment] 2020-03-27 16:47
This is likely a duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/356

**Comment by MattBDev** [comment] 2020-03-27 19:33
Agreed.
Duplicate of #356

**Closed by MattBDev** 2020-03-27 19:33 UTC
