### ISSUE TITLE
Swapping plots does not work with FAWE

### ISSUE THREAD

**Issue by Leahcimkrob** [IntellectualSites/FastAsyncWorldEdit#2076] opened 2023-01-23 17:06 UTC
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

/p swap does not work.
I wanted to swap plot 1;-1 with plot 0;-1.
Plot 1:-1 was copied to plot 0;1.

### To Reproduce

236 / 5.000
Übersetzungsergebnisse
Übersetzung
/p swap does not work.
I wanted to swap plot 1;-1 with plot 0;-1.
I was on plot 0;-1 and typed /p swap 1;-1
Plot 1:-1 was copied to plot 0;1.

### Expected behaviour

Plots 1;-1 and 0;-1 should be swapped.

### Error log (if applicable)

No error

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/26be28aa2eb54b9999b521986497e0cd

### PlotSquared Version

PlotSquared-Bukkit-7.0.0-SNAPSHOT.jar

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment] 2023-01-23 18:35
> > I reworded the title, because I was able to replicate that issue with FAWE only, but not WorldEdit, also on v6, using the same FAWE version like you.
> 
> Would that make it a FAWE issue, not a P^2 issue? I'd be happy to take a gander at this one, just want to be sure of which project is likely the cause. Looking through the logs it looks like there was a failure to handle certain entities, which may have caused it to error mid-run.

Yes, this is a FAWE issue; hence I transferred it to this repository. I would suspect this to be a recent regression, because nobody reported that yet.

**Closed** 2024-01-21 11:42 UTC
Labels: Bug, Approved
