### ISSUE TITLE
JAVA 16 - Error in console 1.16.5

### ISSUE THREAD

**Issue by xCraftRayX** [IntellectualSites/FastAsyncWorldEdit#1032] opened 2021-04-21 14:21 UTC
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

When players disconnecting in console is showing error.
This error was start showing when I started use JAVA 1.16.

### To Reproduce

Join and left from the server

### Expected behaviour

Repair code to remove error from console

### Error log (if applicable)

https://paste.gg/p/anonymous/3a0aaf864c2f4f809f0cbc2d2eddf74d

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/3cb863daf7dc437486c532bb5815ae49

### Fawe Version

1.16-664;cc75654

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by aurorasmiles** [comment] 2021-04-21 14:31
Duplicate of #396 
See also https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1014#issuecomment-814232009

**Closed by aurorasmiles** 2021-04-21 14:31 UTC
Labels: Requires Testing
