### ISSUE TITLE
//gen doesn't accept custom #biome

### ISSUE THREAD

**Issue by Taiyou06** [IntellectualSites/FastAsyncWorldEdit#2707] opened 2024-04-25 21:59 UTC
### What feature do you want to see added?

Would be great if we can use //gen with #biome to biome color stuff faster in larger scale terrain

### Are there any alternatives?

It is possible with brush but it would be a time saver for anyone who works on massive terrains.

**Comment by Taiyou06** [comment] 2024-04-25 22:00
WAsn't really sure if this is a bug or feature request, sorry if it is a bug. 🙏

**Comment by dordsor21** [comment] 2024-06-14 20:48
Most likely duplicate of #2147

**Closed by dordsor21** 2024-06-14 20:48 UTC
Labels: Enhancement
