### ISSUE TITLE
FAWE "Legacy Schematic Issue" | "Index 1048933 out of bounds for length 17113"

### ISSUE THREAD

**Issue by Heyattari** [IntellectualSites/FastAsyncWorldEdit#1177] opened 2021-07-12 08:58 UTC
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

When attempting to paste a schematic, it gives an error in the chat "Please report this error: [check console]" following with the message : "Index 1048933 out of bounds for length 17113" 

Following what console has sent, it gave me a select of errors that flooded console slightly:

Here is the debugpaste; https://athion.net/ISPaster/paste/view/bf8b6691346846f197ede28d0040abcc
	
	

### To Reproduce

1. Join the server
2. Use the command, "//schem load <file name>"
3. Error pops up.

### Expected behaviour

Essentially the load of the schematic should have worked and given me confirmation that it has. . but with this error it's preventing it from doing so.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/87304220/125259458-9e947780-e2ff-11eb-98fa-02fe38dc4b8f.png)

### Error log (if applicable)

https://paste.gg/p/anonymous/dcd3841cebe241b3b851121521e76d40

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/bf8b6691346846f197ede28d0040abcc

### Fawe Version

FastAsyncWorldEdit-Bukkit-1.17-44.jar

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

### Anything else?

Nope

**Comment by NotMyFault** [comment] 2021-07-12 09:08
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1167

**Closed by NotMyFault** 2021-07-12 09:08 UTC
Labels: Requires Testing
