### ISSUE TITLE
Add //setlight back to latest builds for 1.16

### ISSUE THREAD

**Issue by xph11** [IntellectualSites/FastAsyncWorldEdit#694] opened 2020-10-09 08:17 UTC
**Is your feature request related to a problem? Please describe.**
There used to be //setlight command on older versions of minecraft, though it hasn't been present in recent builds for 1.16 versions. Would like to see it back in the plugin as it is very useful 👍 

**Describe the solution you'd like**
Add //setlight back.

**Describe alternatives you've considered**
I tried //setblocklight - says 'temporarily not working' - so that's a nope 💯

**Comment by dordsor21** [comment] 2020-10-09 12:19
duplicate of #254

**Closed by dordsor21** 2020-10-09 12:19 UTC
Labels: [+] Enhancement
