### ISSUE TITLE
//rotate + //paste issue

### ISSUE THREAD

**Issue by psynexus** [IntellectualSites/FastAsyncWorldEdit#1185] opened 2021-07-17 09:16 UTC
### Server Implementation

Paper

### Server Version

1.17.+

### Describe the bug

When attempting to rotate and paste the copied selection, result looks corrupted and throws error.

### To Reproduce

Copy a selection in the world, rotate it and paste it.

### Expected behaviour

A 90-degree rotation and duplication of the selection.

### Error log (if applicable)

https://gist.github.com/psynexus/525549743452ab1f81885b8327c37e59

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/f3206c21154943228d48223110868a59

### Fawe Version

FastAsyncWorldEdit version 1.17-61;275ba9b

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by Tsoccerguy3** [comment] 2021-07-18 15:56
I can confirm this error . 
when rotating
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 20343

**Comment by NotMyFault** [comment] 2021-07-18 15:57
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1167

**Comment by dordsor21** [comment] 2021-07-20 06:16
Reopening in favour of #1167 as that wasn't the same issue at all.

If someone could provide a schematic or screenshot or even just a //distr of a build that causes the error it would be very useful

**Comment by Tsoccerguy3** [comment] 2021-07-20 08:26
https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1167#issuecomment-882086194

**Comment by Tsoccerguy3** [comment] 2021-07-20 08:29
All the information needed was posted in the other issue , including server error .look at the link above

**Comment by dordsor21** [comment] 2021-07-20 09:48
No it wasn't. That was a different issue. Look at my comment above. I was intending for a schematic or a distr because those actually list the blocks. There is far too much build there to see what blocks are there.

**Comment by CS-Birb** [comment] 2021-07-20 11:17
[RotateIssue.zip](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/6847648/RotateIssue.zip)

Reproduced in 1.17-63, running 1.16.5 Purpur 1171. Seems to occur frequently in our buildings, but I've schemed a chunk (attached) as an example.

__Error Stacktrace__
https://gist.github.com/CS-Birb/7fa059ddeb3be2c49afbd683484e23ad

**Comment by CS-Birb** [comment] 2021-07-20 11:50
Appears in my above example the issue is most easily reproducible with right-hinged doors.
No matter their facing, rotating a right-hinged door by 90 degrees seems to cause this issue. 180 degree rotations do not.
Left-hinged doors do not appear to cause this issue.
[RotateDoorSchems.zip](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/6847996/RotateDoorSchems.zip)

Appears to be no difference with upper or lower half of doors, just the side the hinge is on.

**Comment by psynexus** [comment] 2021-07-20 12:11
I didn't have a screenshot, but I experienced what occurred in the screenshot above; namely that I would get a very small portion of the clipboard pasted after the error was thrown. The structure I was trying to paste was very simple, but did contain things like wooden slabs, doors, and trapdoors, which might have contributed to the issue.

**Comment by Tsoccerguy3** [comment] 2021-07-20 14:00
I followed a hunch from CS-Birb . Oak Doors are defiantly 1 cause of the error , if rotated 90 deg in a build , a good portion is missing . maybe other blocks the trigger this as well .

[15:56:34 INFO]: MajorPayne181 issued server command: //copy
[15:56:41 INFO]: MajorPayne181 issued server command: //rotate 90
[15:57:06 INFO]: MajorPayne181 issued server command: //paste
[15:57:06 ERROR]: An unexpected error while handling a WorldEdit command
java.lang.ArrayIndexOutOfBoundsException: null

**Comment by Tsoccerguy3** [comment] 2021-07-20 14:16
![2021-07-20_10 14 39](https://user-images.githubusercontent.com/22108822/126339641-35f88a12-586e-4bca-88e4-f7e45766e29a.png)
![2021-07-20_10 14 59](https://user-images.githubusercontent.com/22108822/126339670-49c9d2f7-5489-479e-a23c-d717bff2660c.png)

**Closed** 2021-07-20 19:49 UTC
Labels: Approved, Bug
