### ISSUE TITLE
Smooth does not work for blocks in the air

### ISSUE THREAD

**Issue by Nishh** [IntellectualSites/FastAsyncWorldEdit#1091] opened 2021-05-25 18:13 UTC
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

//smooth or //brush smooth does not nothing to the blocks in the air.

### To Reproduce

1. place blocks on air (1-2 higher than ground)
2. use smooth in the area (//smooth or //brush smooth)

### Expected behaviour

All the blocks should be lowered to the ground.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/18718300/119547313-9effa000-bd9d-11eb-9c3b-a5a99d7b1ebb.png)

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/8a741ffc59f042358a86f963b5dfdfed

### Fawe Version

FastAsyncWorldEdit version 1.16-688;71f7103

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

### Anything else?

Smooth works if there is a cross block

**Comment by NotMyFault** [comment] 2021-05-25 18:19
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1089
Addressed by PR WIP.

**Closed by NotMyFault** 2021-05-25 18:19 UTC
Labels: Duplicate

**Comment by Nishh** [comment] 2021-07-28 19:28
@NotMyFault this still happens on current latest build (https://ci.athion.net/job/FastAsyncWorldEdit-1.17/99/)

**Comment by NotMyFault** [comment] 2021-07-28 20:25
> @NotMyFault this still happens on current latest build (https://ci.athion.net/job/FastAsyncWorldEdit-1.17/99/)
> should i create a new issue?
> 
> > <img alt="" width="48" src="/static/bcbfc69d/favicon.ico">**[FastAsyncWorldEdit-1.17 #99 [Jenkins]](https://ci.athion.net/job/FastAsyncWorldEdit-1.17/99/)**

Can you link a `/fawe debugpaste` covering the incident described?

**Comment by NotMyFault** [comment] 2021-07-31 13:43
> @NotMyFault that gave me an error: https://pastebin.ubuntu.com/p/Kb8bnTpzXJ/
> Server version: Paper-584 (1.16.5 R0.1)
> 
> > **[Ubuntu Pastebin](https://pastebin.ubuntu.com/p/Kb8bnTpzXJ/)**

Update paper, you are more than 300 updates behind.
