### ISSUE TITLE
Disconnect Error

### ISSUE THREAD

**Issue by DarkTMyt** [IntellectualSites/FastAsyncWorldEdit#1038] opened 2021-04-27 13:52 UTC
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

Hi, I have a little problem when I log out, or a player logs out I get an "InaccessibleObjectException" error, it doesn't look extremely disturbing but it pollutes the console.

### To Reproduce

Install FAWE
Launch your server
Connect to your server
Disconnect

### Expected behaviour

I would just like to know if it was possible to fix it in future versions

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/e008c4915e254e8a8714c96bbb8b1cf5

### Fawe Version

1.16-667;7e3525a

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by SirYwell** [comment] 2021-04-27 13:53
Duplicate of #396

**Closed by SirYwell** 2021-04-27 13:53 UTC
Labels: Duplicate
