### ISSUE TITLE
Missing reference point import from old schematics

### ISSUE THREAD

**Issue by TheoRetisch1** [IntellectualSites/FastAsyncWorldEdit#476] opened 2020-05-21 12:11 UTC
**FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/cddee56fe1914cd5a2ebd8181119201f

**FastAsyncWorldEdit Version Number:** 
WorldEdit version 1.15-245;35c4de3

**Spigot/Paper Version Number:** 
Paper-304 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Description of the problem:**
The reference point from old < 1.15.2 schematics (schematics which are automatically importet using the _mcedit_ format) is not imported. Instead, a new reference point is defined at the outer north-western corner of the schematic.
Why does the reference point matter, if the content is still there? The reference point is crucial: I would estimate that an average of about 80% of the schematics are assets, botany, or structures assigned to specific locations on a map. If assets and trees do not appear in front of you or centered when pasted with or without tools, it makes the desired effective placement in large quantities impossible. All other schematics also have to be pasted more than once without a defined reference point in order to adapt to their target point.
_Conclusion_: If the reference point cannot be imported, most schematics can just be thrown away and be recreated. With the hundreds of schematics you have collected for building structures and landscapes, this can be quite exhausting. It would therefore be worthwhile to make the import possible, even if it may not be easy. 

**How to replicate**:
1. Load one of the two provided test schematics: https://cloud.minecraft-corp.de/index.php/s/TZzbFrSq6jyeYLP
2. //paste
3. The old reference point right in front of the asset does not work, instead FAWE defines a new reference point at the outer north-western corner.

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment] 2020-07-03 14:24
duplicate of #454

**Closed by dordsor21** 2020-07-03 14:24 UTC
Labels: Requires Testing
