### ISSUE TITLE
InaccessibleObjectException when logging out

### ISSUE THREAD

**Issue by marazmarci** [IntellectualSites/FastAsyncWorldEdit#1012] opened 2021-04-05 00:21 UTC
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

Everytime a user logs out, a WARN log appears in the server log about an InaccessibleObjectException.
It's not fatal, it doesn't crash the server. (see the attached error log)
I'm using AdoptOpenJDK 16 for aarch64.
(jdk-16+36; 2021-03-20-11-15)
https://github.com/AdoptOpenJDK/openjdk16-binaries/releases/download/jdk16u-2021-03-20-11-15/OpenJDK16U-jdk_aarch64_linux_hotspot_2021-03-20-11-15.tar.gz

### To Reproduce

1. use (AdoptOpen)JDK 16
2. have FAWE installed on a Paper server
3. log a user out

### Expected behaviour

no exception thrown when a user logs out

### Error log (if applicable)

https://haste.athion.net/iqexujubaf.md

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/34424efd16a74034bae7dd6261e91429

### Fawe Version

1.16-641;a988a0d

### Checklist

I have included a Fawe debugpaste.
I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.16/ and the issue still persists.

**Comment by HSGamer** [comment] 2021-04-08 03:46
This can be related: https://stackoverflow.com/questions/41265266/how-to-solve-inaccessibleobjectexception-unable-to-make-member-accessible-m

**Comment by NotMyFault** [comment] 2021-04-12 11:27
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/396

**Closed by NotMyFault** 2021-04-12 11:27 UTC
Labels: Requires Testing
