### ISSUE TITLE
regen no working on 1.16.5 paper

### ISSUE THREAD

**Issue by dan28000** [IntellectualSites/FastAsyncWorldEdit#2139] opened 2023-03-08 15:35 UTC
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

When trying to use regen on 1.16.5 it throws error

### To Reproduce

start paper server 1.16.5 with latest fawe as of now it's build 381 make a selection region and try to run //regen

### Expected behaviour

not throw error and do the regen properly

### Error log (if applicable)

https://paste.gg/p/anonymous/77e4fb8ec0764ca0bfa76ddcc6fd1404

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/1987146deea44351b212e490c28d3e8c

### Fawe Version

2.5.3-SNAPSHOT-381;bfd919b

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment] 2023-03-18 14:29
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/2035

**Closed by NotMyFault** 2023-03-18 14:29 UTC
Labels: Duplicate
