### ISSUE TITLE
Spawning vanilla structures

### ISSUE THREAD

**Issue by jrenslo** [IntellectualSites/FastAsyncWorldEdit#2720] opened 2024-05-08 13:53 UTC
### What feature do you want to see added?

Add support for spawning vanilla structures akin to the vanilla /place command, and worldedit's undocumented //feature command

### Are there any alternatives?

vanilla worldedit

can also use vanilla /place, then //cut and //paste, but its cumbersome. Also given the commands already exist I imagine it might not be a heavy lift? (maybe hopefully? 👍 )

**Comment by jrenslo** [comment] 2024-05-08 13:55
the command might actually be //structure in worldedit

**Comment by jrenslo** [comment] 2024-05-08 14:31
Note, these are new changes in WE 7.3.0

relevant command section:
https://github.com/EngineHub/WorldEdit/blob/e2e916335477d5c02649aaeff2f81a0a2d43daa7/worldedit-core/src/main/java/com/sk89q/worldedit/command/GenerationCommands.java#L301
https://github.com/EngineHub/WorldEdit/blob/e2e916335477d5c02649aaeff2f81a0a2d43daa7/worldedit-core/src/main/java/com/sk89q/worldedit/command/GenerationCommands.java#L284

they call the generateFeature and generateStructure methods within specific World classes as the world adapter requires
(e.g. https://github.com/EngineHub/WorldEdit/blob/master/worldedit-fabric/src/main/java/com/sk89q/worldedit/fabric/FabricWorld.java#L489)

**Comment by dordsor21** [comment] 2024-05-12 08:48
Duplicate of #2343

**Closed by dordsor21** 2024-05-12 08:48 UTC
Labels: Enhancement
